package co.gov.policia.dinae.constantes;

/**
 *
 * @author Rafael Guillermo Blanco Banquez <rafaelg.blancob@gmail.com>
 */
public interface IConstantesRole {

    Long ADMINISTRADOR_DE_INVESTIGACION_SIGAC_EN_LA_UNIDAD_POLICIAL = 1L;
    Long ADMINISTRADOR_DE_PARAMETROS_DEL_SISTEMA = 2L;
    Long ADMINISTRADOR_DE_USUARIOS_DEL_SISTEMA = 3L;
    Long AUTORIZADO_PARA_REGISTRAR_PROPUESTAS_EN_CONVOCATORIAS_EN_LA_UNIDAD_POLICIAL = 4L;
    Long AUTORIZADO_PARA_REGISTRO_DE_NECESIDADES_EN_LA_UNIDAD_POLICIAL = 5L;
    Long ENCARGADO_DE_INVESTIGADORES_EN_LA_UNIDAD_POLICIAL = 6L;
    Long ENCARGADO_DE_CONVOCATORIAS_EN_VICIN = 7L;
    Long ENCARGADO_DE_ENSAYOS_EN_LA_UNIDAD_POLICIAL = 8L;
    Long ENCARGADO_DE_EVALUACION_DE_ENSAYOS_EN_LA_VICIN = 9L;
    Long ENCARGADO_DE_EVENTOS_EN_LA_VICIN = 10L;
    Long ENCARGADO_DE_GESTION_DE_COMPROMISOS_VICIN = 11L;
    Long ENCARGADO_DE_HABILITAR_IMPLEMENTACION_DE_PROYECTOS_EN_VICIN = 12L;
    Long ENCARGADO_DE_LA_EVALUACION_DE_LOS_PROYECTOS_DE_INVESTIGACION_VICIN = 13L;
    Long ENCARGADO_DE_PERIODOS_DE_PROPUESTAS_DE_NECESIDADES_EN_VICIN = 14L;
    Long ENCARGADO_DE_REVISION_DE_COMPROMISOS_DE_PROYECTOS_DE_CONVOCATORIA_VICIN = 15L;
    Long ENCARGADO_DE_REVISION_DE_COMPROMISOS_DE_PROYECTOS_INSTITUCIONALES_VICIN = 16L;
    Long ENCARGADO_DE_SEMILLEROS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL = 17L;
    Long EVALUADOR_DE_PROPUESTAS_DE_CONVOCATORIAS_EN_LA_VICIN = 18L;
    Long EVALUADOR_DE_PROPUESTAS_DE_NECESIDADES_EN_LA_VICIN = 19L;
    Long GENERADOR_DE_CONSULTA_DE_CONVOCATORIAS = 20L;
    Long GENERADOR_DE_CONSULTA_DE_INVESTIGADORES = 21L;
    Long GENERADOR_DE_CONSULTA_DE_SEMILLEROS = 22L;
    Long GENERADOR_DE_CONSULTAS = 23L;
    Long JEFE_DE_LA_UNIDAD_POLICIAL = 24L;
    Long JEFE_DEL_GRUPO_DE_INVESTIGACION_EN_LA_UNIDAD = 25L;
    Long RESPONSABLE_DE_LA_IMPLEMENTACION_EN_LA_UNIDAD_POLICIAL = 26L;

    Long RESPONSABLE_DE_PROYECTOS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL = 27L;
    Long RESPONSABLE_DE_TRABAJOS_DE_GRADO_EN_LA_ESCUELA = 28L;
    Long USUARIO_DEL_SISTEMA = 29L;
    Long INVESTIGADOR_PRINCIPAL = 30L;
    Long AUTORIZADO_PARA_REALIZAR_ASESORIAS_EN_LA_VICIN = 31L;
    Long INVESTIGADOR_PRINCIPAL_TRABAJO_GRADO = 32L;
    Long ENCARGADO_GENERACION_ARCHIVO_SNIES = 33L;

    Long VICERRECTORIA_INVESTIGACION_VICIN = 34L;
    Long INVESTIGADORES_RESPONSABLES_INVESTIGACION_EXTERNA = 35L;
    Long DIRECTOR_GRUPO_INVESTIGACION = 36L;
    Long USUARIO_UNIDAD = 37L;

    /**
     * @Autor : Andrés Felipe Zamora Garzón Roles Educación Continua Fecha :
     * 05-10-2016
     */
    Long PARAMETRIZADOR_PAE = 41L;
    Long PARAMETRIZADOR_PROGRAMA_EDUCACION_CONTINUA = 42L;
    Long PARAMETRIZADOR_EVALUACION_EDUCACION_CONTINUA = 43L;
    Long PARAMETRIZADOR_DESARROLLO_PAE = 44L;
    Long ADMINISTRADOR_SISTEMA = 45L;
    Long SEGUIMIENTO_ESTRATEGIA = 46L;

    /**
     * @Autor : Andrés Felipe Zamora Garzón Roles Secretaría Académica Fecha :
     * 10-12-2017
     */
    Long SECRETARIA_ACADEMICA = 38L;
    Long REGISTRO_CONTROL = 39L;
    Long DOCENTE = 40L;

    Long[] ROLES_UNIDAD = {
        ADMINISTRADOR_DE_INVESTIGACION_SIGAC_EN_LA_UNIDAD_POLICIAL,
        AUTORIZADO_PARA_REGISTRAR_PROPUESTAS_EN_CONVOCATORIAS_EN_LA_UNIDAD_POLICIAL,
        AUTORIZADO_PARA_REGISTRO_DE_NECESIDADES_EN_LA_UNIDAD_POLICIAL,
        ENCARGADO_DE_INVESTIGADORES_EN_LA_UNIDAD_POLICIAL,
        ENCARGADO_DE_ENSAYOS_EN_LA_UNIDAD_POLICIAL,
        ENCARGADO_DE_SEMILLEROS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL,
        GENERADOR_DE_CONSULTA_DE_CONVOCATORIAS,
        GENERADOR_DE_CONSULTA_DE_INVESTIGADORES,
        GENERADOR_DE_CONSULTA_DE_SEMILLEROS,
        GENERADOR_DE_CONSULTAS,
        RESPONSABLE_DE_LA_IMPLEMENTACION_EN_LA_UNIDAD_POLICIAL,
        RESPONSABLE_DE_PROYECTOS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL,
        RESPONSABLE_DE_TRABAJOS_DE_GRADO_EN_LA_ESCUELA,
        USUARIO_DEL_SISTEMA,
        INVESTIGADOR_PRINCIPAL,
        PARAMETRIZADOR_DESARROLLO_PAE,
        //INVESTIGADOR_PRINCIPAL_TRABAJO_GRADO,
        ENCARGADO_GENERACION_ARCHIVO_SNIES
    };

    Long[] ROLES_VICIN = {
        ADMINISTRADOR_DE_PARAMETROS_DEL_SISTEMA,
        ADMINISTRADOR_DE_USUARIOS_DEL_SISTEMA,
        ENCARGADO_DE_CONVOCATORIAS_EN_VICIN,
        ENCARGADO_DE_EVALUACION_DE_ENSAYOS_EN_LA_VICIN,
        ENCARGADO_DE_EVENTOS_EN_LA_VICIN,
        ENCARGADO_DE_GESTION_DE_COMPROMISOS_VICIN,
        ENCARGADO_DE_HABILITAR_IMPLEMENTACION_DE_PROYECTOS_EN_VICIN,
        ENCARGADO_DE_LA_EVALUACION_DE_LOS_PROYECTOS_DE_INVESTIGACION_VICIN,
        ENCARGADO_DE_PERIODOS_DE_PROPUESTAS_DE_NECESIDADES_EN_VICIN,
        ENCARGADO_DE_REVISION_DE_COMPROMISOS_DE_PROYECTOS_DE_CONVOCATORIA_VICIN,
        ENCARGADO_DE_REVISION_DE_COMPROMISOS_DE_PROYECTOS_INSTITUCIONALES_VICIN,
        EVALUADOR_DE_PROPUESTAS_DE_CONVOCATORIAS_EN_LA_VICIN,
        EVALUADOR_DE_PROPUESTAS_DE_NECESIDADES_EN_LA_VICIN,
        GENERADOR_DE_CONSULTAS,
        GENERADOR_DE_CONSULTA_DE_SEMILLEROS,
        GENERADOR_DE_CONSULTA_DE_INVESTIGADORES,
        AUTORIZADO_PARA_REALIZAR_ASESORIAS_EN_LA_VICIN,
        GENERADOR_DE_CONSULTA_DE_CONVOCATORIAS,        
        ENCARGADO_GENERACION_ARCHIVO_SNIES};

    Long[] ROLES_DEPENDE_JEFE_GRUPO_INVESTIGACION_UNIDAD = {
        ENCARGADO_DE_ENSAYOS_EN_LA_UNIDAD_POLICIAL,
        ENCARGADO_DE_SEMILLEROS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL,
        RESPONSABLE_DE_TRABAJOS_DE_GRADO_EN_LA_ESCUELA,
        RESPONSABLE_DE_LA_IMPLEMENTACION_EN_LA_UNIDAD_POLICIAL,
        AUTORIZADO_PARA_REGISTRAR_PROPUESTAS_EN_CONVOCATORIAS_EN_LA_UNIDAD_POLICIAL,
        ENCARGADO_DE_INVESTIGADORES_EN_LA_UNIDAD_POLICIAL,
        RESPONSABLE_DE_PROYECTOS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL,
        AUTORIZADO_PARA_REGISTRO_DE_NECESIDADES_EN_LA_UNIDAD_POLICIAL,
        JEFE_DEL_GRUPO_DE_INVESTIGACION_EN_LA_UNIDAD};

    Long[] ROLES_DEPENDE_JEFE_INVESTIGACION_SIGAC_UNIDAD = {
        RESPONSABLE_DE_LA_IMPLEMENTACION_EN_LA_UNIDAD_POLICIAL,
        AUTORIZADO_PARA_REGISTRAR_PROPUESTAS_EN_CONVOCATORIAS_EN_LA_UNIDAD_POLICIAL,
        ENCARGADO_DE_INVESTIGADORES_EN_LA_UNIDAD_POLICIAL,
        RESPONSABLE_DE_PROYECTOS_DE_INVESTIGACION_EN_LA_UNIDAD_POLICIAL,
        AUTORIZADO_PARA_REGISTRO_DE_NECESIDADES_EN_LA_UNIDAD_POLICIAL};

    Long[] ROLES_SECRETARIA_ACADEMICA = {
        SECRETARIA_ACADEMICA,
        REGISTRO_CONTROL,
        DOCENTE
    };

    Long[] ROLES_VICERRECTORIA_EDUCACION_CONTINUA = {
        PARAMETRIZADOR_PAE,
        PARAMETRIZADOR_PROGRAMA_EDUCACION_CONTINUA,
        PARAMETRIZADOR_EVALUACION_EDUCACION_CONTINUA,       
        ADMINISTRADOR_SISTEMA,
        SEGUIMIENTO_ESTRATEGIA
    };

}
