package co.gov.policia.dinae.constantes;

/**
 *
 * @author Rafael Guillermo Blanco Banquez <rafael.blanco@pointmind.com>
 */
public interface IConstantes {

  //CONSTANTE ORIGEN COMENTARIOS COMPROMISO PROYECTOS CU_PR_25
  String ORIGEN_COMENTARIO_COMPROMISO_PROYECTO_CU_PR_25 = "CU_PR_25";
  //CONSTANTE ORIGEN COMENTARIOS COMPROMISO PROYECTOS CU_PR_24
  String ORIGEN_COMENTARIO_COMPROMISO_PROYECTO_CU_PR_24 = "CU_PR_24";

  //CONSTANTE ORIGEN COMPROMISO CU_PR_25
  String ORIGEN_COMPROMISO_PROYECTO = "ORIGEN_COMPROMISO_PROYECTO";
  String ORIGEN_COMPROMISO_IMPLEMENTACION = "ORIGEN_COMPROMISO_IMPLEMENTACION";

  //CONSTANTES TEMA PROYECTO
  String DESTINO_TEMA_CU_PR_01_PROYECTO = "CU_PR_01_PROYECTO";
  String DESTINO_TEMA_CU_PR_15_INFO_AVANCE_PROCESO = "CU_PR_15_INFO_AVANCE_PROCESO";
  String DESTINO_TEMA_CU_PR_15_AVANCE_FINAL_PROCESO = "CU_PR_15_AVANCE_FINAL_PROCESO";
  String DESTINO_TEMA_CU_PR_15_AVANCE_INFOR_TENER_CUENTA = "CU_PR_15_AVANCE_INFOR_TENER_CUENTA";
  String DESTINO_TEMA_CU_PR_15_FINAL_INFOR_TENER_CUENTA = "CU_PR_15_FINAL_INFOR_TENER_CUENTA";
  String DESTINO_TEMA_CU_PR_15_TAB_6_INFORMACION_TENER_EN_CUENTA_AVANCE = "CU_PR_15_TAB_6_INFORMACION_TENER_EN_CUENTA_AVANCE";
  String DESTINO_TEMA_CU_PR_15_TAB_6_INFORMACION_TENER_EN_CUENTA_AVANCE_FINAL = "CU_PR_15_TAB_6_INFORMACION_TENER_EN_CUENTA_AVANCE_FINAL";
  String DESTINO_TEMA_PR_15_TAB_2_AVANCE_SOBRE_PROCESO = "CU_PR_15_TAB_2_AVANCE_SOBRE_PROCESO";
  String DESTINO_TEMA_PR_15_TAB_2_FINAL_RESULTADO_OBTENIDO = "CU_PR_15_TAB_2_FINAL_RESULTADO_OBTENIDO";

  //CONSTANTES PARA ADMINISTRAR EL CAMPO ORIGEN_SIAF_O_INVESTI DE LA TABLA INVESTIGADORES_PROYECTO
  Character ORIGEN_INVESTIGADOR_PROYECTO_SIAFT = 'S';
  Character ORIGEN_INVESTIGADOR_PROYECTO_INVESTIGADOR = 'I';

  //ESTADO DE LOS ENVIO DE CORREO
  String ESTADO_CORREO_ENVIO_FALLIDO = "FALLIDO";
  String ESTADO_CORREO_ENVIO_EXITOSO = "EXITOSO";

  //CODIGO UNICOS DE LOS CORREOS
  String CU_NE_01_PERIODO_PUBLICADO = "CU_NE_01_PERIODO_PUBLICADO";
  String CU_NE_02_JEFES_UNIDAD = "CU_NE_02_JEFES_UNIDAD";
  String CU_NE_05_ENVIO_PROPUESTA_VICIN = "CU_NE_05_ENVIO_PROPUESTA_VICIN";
  String CU_NE_05_PROPUESTAS_NO_ACEPTADAS = "CU_NE_05_PROPUESTAS_NO_ACEPTADAS";
  String CU_NE_06_RESULTADO_REVISION = "CU_NE_06_RESULTADO_REVISION";
  String CU_CO_01_PUBLICACION_CONVOCATORIA_FINANCIACION = "CU_CO_01_PUBLICACION_CONVOCATORIA";
  String CU_CO_01_PUBLICACION_CONVOCATORIA_ENSAYO = "CU_CO_01_PUBLICACION_CONVOCATORIA_ENSAYO";
  String CU_CO_02_ENVIO_PROPUESTA_REVISION = "CU_CO_02_ENVIO_PROPUESTA_REVISION";
  String CU_PR_01_FORMULARIO_JEFE_UNIDAD = "CU_PR_01_FORMULARIO_JEFE_UNIDAD";
  String CU_CO_03_JEFE_UNIDAD_NOACEPTA_PROPUESTA = "CU_CO_03_JEFE_UNIDAD_NOACEPTA_PROPUESTA";
  String CU_CO_03_JEFE_UNIDAD_ENVIA_PROP_CONVOCATO_VICIN = "CU_CO_03_JEFE_UNIDAD_ENVIA_PROP_CONVOCATO_VICIN";
  String CU_CO_04_PUBLICAR_RESULTADOS = "CU_CO_04_PUBLICAR_RESULTADOS";
  String CU_PR_07_ENVIO_COMPROMISO_INFORME = "CU_PR_07_ENVIO_COMPROMISO_INFORME";
  String CU_PR_25_GRUPO_INVESTIGACION = "CU_PR_25_GRUPO_INVESTIGACION";
  String CU_PR_25_VICIN = "CU_PR_25_VICIN";
  String CU_PR_24_INFORMA_CORRECCION_COMPROMISO = "CU_PR_24_INFORMA_CORRECCION_COMPROMISO";
  String CU_PR_23_INFORMAR_CAMBIO_FECHA_COMPROMISO = "CU_PR_23_INFORMAR_CAMBIO_FECHA_COMPROMISO";
  String CU_PR_23_INFORMAR_CAMBIO_RESPONSABLE = "CU_PR_23_INFORMAR_CAMBIO_RESPONSABLE";
  String CU_CO_08_INFORMAR_ENVIO_ENSAYOS_PREVIO_REVISA = "CU_CO_08_INFORMAR_ENVIO_ENSAYOS_PREVIO_REVISA";
  String CU_CO_10_INFORMAR_RESULTADO_EVALUACION_ENSAYOS = "CU_CO_10_INFORMAR_RESULTADO_EVALUACION_ENSAYOS";

  String CLAVE_INDICADOR_BASE_CASO_USO_PR_04 = "CU_CO_04";
  String CLAVE_INDICADOR_BASE_CASO_USO_PR_01 = "CU_PR_01";
  String CLAVE_INDICADOR_BASE_CASO_USO_PR_07 = "CU_PR_07";

  Character YES_Y = 'Y';
  Character NO_N = 'N';

  //TIPOS - TABLA CONSTANTES
  String TIPO_HITO_PERIODO = "TIPO_HITO_PERIODO";
  String TIPO_GRADO_FUNCIONARIO = "GRADO_FUNCIONARIO";
  String TIPO_PROPUESTA_NECESIDAD = "TIPO_PROPUESTA_NECESIDAD";
  String TIPO_ROL_PROYECTO_NECESIDAD = "TIPO_ROL_PROYECTO_NECESIDAD";
  String TIPO_COMPROMISO_NECESIDAD_PROYECTO = "TIPO_COMPROMISO_NECESIDAD_PROYECTO";
  String TIPO_COMPROMISO_COMPROMISO = "TIPO_COMPROMISO_COMPROMISO";
  String TIPO_COMPROMISO_PERIODO = "TIPO_COMPROMISO_PERIODO";
  String TIPO_CONVOCATORIA_GESTION = "TIPO_CONVOCATORIA_GESTION";
  String TIPO_VINCULACION_PROYECTO = "TIPO_VINCULACION_PROYECTO";
  String TIPO_INVESTIGADOR_PROYECTO = "TIPO_INVESTIGADOR_PROYECTO";
  String LDAP_JNDI_WEBLOGIC_PARAM = "LDAP_JNDI_WEBLOGIC_PARAM";
  String LDAP_JNDI_WEBLOGIC_PATRON_BUSQUEDA = "LDAP_JNDI_WEBLOGIC_PATRON_BUSQUEDA";
  String LDAP_JNDI_WEBLOGIC_ATRIBUTO_BUSQUEDA = "LDAP_JNDI_WEBLOGIC_ATRIBUTO_BUSQUEDA";
  String TIPO_CONFIGURACION_MAIL_DINAE_PARAM = "TIPO_CONFIGURACION_MAIL_DINAE_PARAM";
  String TIPO_CONFIGURACION_MAIL_DINAE_USUARIO = "TIPO_CONFIGURACION_MAIL_DINAE_USUARIO";
  String TIPO_CONFIGURACION_MAIL_DINAE_CLAVE = "TIPO_CONFIGURACION_MAIL_DINAE_CLAVE";
  String TIPO_CONFIGURACION_MAIL_DINAE_DEBUG_MAIL = "TIPO_CONFIGURACION_MAIL_DINAE_DEBUG_MAIL";
  String TIPO_FUENTE_FINANCIERA = "TIPO_FUENTE_FINANCIERA";
  String NOMBRE_FUENTE_FINANCIERA_CONSTANTE = "NOMBRE_FUENTE_FINANCIERA_CONSTANTE";
  String TIPO_ESTADO_PROPUESTA_CONVOCATORIA = "TIPO_ESTADO_PROPUESTA_CONVOCATORIA";
  String TIPO_CRITERIO_EVALUAR_PROPUESTA_CONVOCATORIA = "TIPO_CRITERIO_EVALUAR_PROPUESTA_CONVOCATORIA";
  String TIPO_ITEM_COMENTARIO_REVISION_PROYECTO = "TIPO_ITEM_COMENTARIO_REVISION_PROYECTO";
  String DURACION_PROYECTO_CONVOCATORIA_INSTITUCIONAL = "DURACION_PROYECTO_CONVOCATORIA_INSTITUCIONAL";
  String TIPO_INDICADORES_GENERALES_PROYECTO = "TIPO_INDICADORES_GENERALES_PROYECTO";
  //String TIPO_INDICADORES_GENERALES_PROYECTO_CU_07 = "TIPO_INDICADORES_GENERALES_PROYECTO_CU_07";
  String TIPO_EVIDENCIA_TIPO_ARCHIVO = "TIPO_EVIDENCIA_TIPO_ARCHIVO";
  String TIPO_RESULTADO_RETROALIMENTACION_COMPROMISO = "TIPO_RESULTADO_RETROALIMENTACION_COMPROMISO";
  String TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL = "TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL";

  String CODIGO_DURACION_PROYECTOS_DE_CONVOCATORIA = "DURACION_PROYECTOS_DE_CONVOCATORIA";
  String CODIGO_DURACION_PROYECTOS_INSTITUCIONALES = "DURACION_PROYECTOS_INSTITUCIONALES";
  String CODIGO_CANTIDAD_DE_SEMANAS_POR_MES = "CANTIDAD_DE_SEMANAS_POR_MES";

  String TIPO_INSTITUCIONES_PARTICIPANTES_PROYECTO = "TIPO_INSTITUCIONES_PARTICIPANTES_PROYECTO";
  String TIPO_ESTADO_RESULTADO_COMPROMISO_PROYECTO = "TIPO_ESTADO_RESULTADO_COMPROMISO_PROYECTO";

  //ESTADOS PARA AMDINISTRAR LOS MENUS
  String ESTADO_MENU_PUBLICO = "PUBLICO";
  String ESTADO_MENU_PRIVADO = "PRIVADO";
  String ESTADO_MENU_LOGUEADO = "LOGUEADO";

  String ESTADO_ACTIVO_CRITERIO_EVALUACION = "ACTIVO";
  String ESTADO_INACTIVO_CRITERIO_EVALUACION = "INACTIVO";

  String TIPO_CRITERIO_EVALUACION_PROPUESTA_FINANCIACION = "FINANCIACION";
  String TIPO_CRITERIO_EVALUACION_PROPUESTA_ENSAYO_CRITICO = "ENSAYO_CRITICO";
  String TIPO_CRITERIO_EVALUACION_PROYECTO = "EVALUACION_PROYECTO";

  //ESTADOS DE LOS PERIODOS
  Character ESTADO_PERIODO_TEMPORAL = 'T';
  Character ESTADO_PERIODO_PUBLICADO = 'P';

  Long TIPO_HITO_PERIODO_ID_INFORME_DE_AVANCE = 1L;
  Long TIPO_HITO_PERIODO_ID_INFORME_FINAL = 2L;

  //TIPO DE HITOS
  String TIPO_HITO_PERIODO_INFORME_FINAL = "Informe Final";
  String TIPO_HITO_PERIODO_INFORME_DE_AVANCE = "Informe De Avance";

  String PROPUESTA_NECESIDAD_ENVIADA_A_VICIN = "ENVIADA_A_VICIN";
  String PROPUESTA_NECESIDAD_PUBLICADA_JEFE_UNIDAD = "PUBLICADA_JEFE_UNIDAD";

  //CONSTANTES ESTADOS PROPUESTA NECESIDAD
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_EN_ELABORACION = 3L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_APROBACION_JEFE_UNIDAD = 4L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_ENVIADA_A_VICIN = 12L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_REVISADA = 13L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_PRE_APROBADA = 14L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_APROBADA = 15L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_RECHAZADA = 16L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_NO_APROBADA = 17L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_NO_ACEPTADA = 18L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_ACEPTADA = 19L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_COPIADA = 29L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_SIN_ENVIAR = 2007L;
  Long CONSTANTES_ESTADO_PROPUESTA_NECESIDAD_OBSERVADO = 2008L;

  Integer MAXIMO_MES_AGREGAR_PERIODO_ANIO_ACTUAL = 10;

  Long CONSTANTE_TIPO_ROL_PROYECTO_NECESIDAD_RESPONSABLE = 20L;
  Long CONSTANTE_TIPO_ROL_PROYECTO_NECESIDAD_DE_APOYO = 21L;

  //CONSTANTES TIPO_COMPROMISO_NECESIDAD_PROYECTO
  Long TIPO_COMPROMISO_NECESIDAD_DE_CONVOCATORIA_DE_FINANCIACION = 22L;
  Long TIPO_COMPROMISO_NECESIDAD_DE_PROYECTOS_INSTITUCIONALES = 23L;

  //CONSTANTES COMPROMISO_PERIODO
  Long COMPROMISO_PERIODO_FORMULACION_DEL_PROYECTO = 26L;
  Long COMPROMISO_PERIODO_INFORME_DE_AVANCE = 27L;
  Long COMPROMISO_PERIODO_INFORME_DE_AVANCE_DOS = 2010L;
  Long COMPROMISO_PERIODO_INFORME_FINAL = 28L;

  Long TIPO_INVESTIGADOR_PROYECTO_INVESTIGADOR_PRINCIPAL = 30L;
  Long TIPO_INVESTIGADOR_PROYECTO_CO_INVESTIGADOR = 31L;
  Long TIPO_INVESTIGADOR_PROYECTO_ASESOR = 32L;
  Long TIPO_INVESTIGADOR_PROYECTO_AUXILIAR_DE_INVESTIGACION = 33L;

  Long TIPO_CONVOCATORIA_GESTION_PARA_FINANCIACION = 38L;
  Long TIPO_CONVOCATORIA_GESTION_ENSAYO_CRITICO = 39L;

  String TIPO_ESTADO_CONVOCATORIA = "TIPO_ESTADO_CONVOCATORIA";

  Long TIPO_ESTADO_CONVOCATORIA_NUEVA = 40L;
  Long TIPO_ESTADO_CONVOCATORIA_PUBLICADA = 41L;
  Long TIPO_ESTADO_CONVOCATORIA_ABIERTA = 42L;
  Long TIPO_ESTADO_CONVOCATORIA_EN_EVALUACION = 43L;
  Long TIPO_ESTADO_CONVOCATORIA_EN_EJECUCION = 44L;
  Long TIPO_ESTADO_CONVOCATORIA_CULMINADA = 45L;
  //CLAVE KEY PROPERTIES
  String CLAVE_KP_CU_CU_CO_1_LBL_NUMERO_CONVOCATORIA_FINANCIA_NUM = "cu_co_1_lbl_numero_convocatoria_financia_num";
  String CLAVE_KP_CU_CU_CO_1_LBL_NUMERO_CONVOCATORIA_ENSAYO_NUM = "cu_co_1_lbl_numero_convocatoria_ensayo_num";

  Character FUNCIONARIO_INVESTIGADOR_ACTIVO = 'Y';
  Character FUNCIONARIO_INVESTIGADOR_NO_ACTIVO = 'N';

  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_EN_ELABORACION = 80L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_EN_REVISION_DE_JEFE_DE_LA_UNIDAD = 81L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_NO_ACEPTADO_POR_JEFE_DE_UNIDAD = 82L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_ACEPTADO_POR_JEFE_DE_UNIDAD = 83L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_ENVIADA_A_VICIN = 84L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_EVALUADA = 85L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_NO_APROBADA = 86L;
  Long TIPO_ESTADO_PROPUESTA_CONVOCATORIA_PARA_FINALIZAR = 87L;

  Long TIPO_ITEM_COMENTARIO_REVISION_PROYECTO_OBJETIVO = 88L;
  Long TIPO_ITEM_COMENTARIO_REVISION_PROYECTO_PLANTEAMIENTO_DEL_PROYECTO = 89L;
  Long TIPO_ITEM_COMENTARIO_REVISION_PROYECTO_INDICADORES = 90L;
  Long TIPO_ITEM_COMENTARIO_REVISION_PROYECTO_OTRO = 91L;

  Long DURACION_PROYECTOS_DE_CONVOCATORIA = 92L;
  Long DURACION_PROYECTOS_INSTITUCIONALES = 93L;
  Long CANTIDAD_DE_SEMANAS_POR_MES = 94L;

  Long TIPO_INSTITUCIONES_PARTICIPANTES_PROYECTO_COLCIENCIAS = 95L;
  Long TIPO_INSTITUCIONES_PARTICIPANTES_PROYECTO_MINISTERIO_DE_DEFENSA = 96L;
  Long TIPO_INSTITUCIONES_PARTICIPANTES_PROYECTO_INVESTIGARE = 97L;
  Long TIPO_INSTITUCIONES_PARTICIPANTES_PROYECTO_OTRO = 109L;

  String ESTADO_TEMPORAL_PROPUESTA_FINANCIA_APROBADA = "APROBADA";
  String ESTADO_TEMPORAL_PROPUESTA_FINANCIA_NO_APROBADA = "NO_APROBADA";

  String TIPO_FUENTE_FINANCIERA_INTERNA = "Interna";
  Long ID_TIPO_FUENTE_FINANCIERA_INTERNA = 116L;
  String TIPO_FUENTE_FINANCIERA_EXTERNA = "Externa";
  Long ID_TIPO_FUENTE_FINANCIERA_EXTERNA = 115L;

  Long TIPO_ESTADO_PROYECTO_EN_EJECUCION = 110L;
  Long TIPO_ESTADO_PROYECTO_CULMINADO = 111L;
  Long TIPO_ESTADO_PROYECTO_EVALUADO = 112L;
  Long TIPO_ESTADO_PROYECTO_EN_IMPLEMENTACION = 113L;
  Long TIPO_ESTADO_PROYECTO_IMPLEMENTADO = 114L;

  String TIPO_ESTADO_PROYECTO = "TIPO_ESTADO_PROYECTO";

  String LUGAR_GEOGRAFICO_COLOMBIA = "COLOMBIA";
  Long CODIGO_LUGAR_GEOGRAFICO_COLOMBIA = 10L;
  Long CODIGO_LUGAR_GEOGRAFICO_BOGOTA = 1227L;
  String TIPO_GASTOS_EVENTOS_RELACIONADOS = "TIPO_GASTO_EVENTO_RELACIONADO";
  String TIPO_ORIGEN_EQUIPO_INVESTIGACION = "ORIGEN_EQUIPO_INVESTIGACION";

  Long ESTADO_COMPROMISO_PROYECTO_PENDIENTE = 100L;
  Long ESTADO_COMPROMISO_PROYECTO_CUMPLIDO = 107L;
  Long ESTADO_COMPROMISO_PROYECTO_CORRECCION_COMPROMISO = 108L;
  Long ESTADO_COMPROMISO_PROYECTO_EN_REVISION_DEL_JEFE = 117L;
  Long ESTADO_COMPROMISO_PROYECTO_ENVIADO_A_VICIN = 118L;
  Long ESTADO_COMPROMISO_PROYECTO_EN_ELABORACION = 178L;
  Long ESTADO_COMPROMISO_PROYECTO_ACEPTADO = 179L;
  Long ESTADO_COMPROMISO_PROYECTO_REVISADO = 180L;
  Long ESTADO_COMPROMISO_PROYECTO_NO_ACEPTADO = 181L;

  String INFORME_AVANCE_FINAL_TIPO_PRODUCTO = "INFORME_AVANCE_FINAL_TIPO_PRODUCTO";
  Long TIPO_INFORME_AVANCE_INICIAL = 147L;
  Long TIPO_INFORME_AVANCE_AVANCE = 148L;
  Long TIPO_INFORME_AVANCE_FINAL = 149L;

  String AREAS_SABER_INVESTIGADOR = "AREA_SABER_INVESTIGADOR";
  String NIVEL_FORMACION_INVESTIGADOR = "NIVEL_FORMACION_INVESTIGADOR";
  String TIPO_PUBLICACION_INVESTIGADOR = "TIPO_PUBLICACION_INVESTIGADOR";

  Long ID_NOMBRE_FUENTE_FINANCIERA_CONSTANTE_POLICIA_DINAE = 99L;
  Long ID_NOMBRE_FUENTE_FINANCIERA_CONSTANTE_PONAL = 98L;

  Long TIPO_PUBLICACION_ARTICULO_EN_REVISTA = 171L;
  Long TIPO_PUBLICACION_ARTICULO_EN_REVISTA_INDEXADA = 172L;
  Long TIPO_PUBLICACION_LIBRO = 173L;
  Long TIPO_PUBLICACION_CAPITULO_EN_LIBRO = 174L;
  Long TIPO_PUBLICACION_OTRO = 175L;

  String OTROS_GASTOS_RUBROS = "OTROS_GASTOS_RUBROS";
  String OTROS_GASTOS_TIPO = "OTROS_GASTOS_TIPO";

  Long OTROS_GASTOS_RUBROS_GASTOS_ADMINISTRATIVOS = 182L;
  Long OTROS_GASTOS_RUBROS_PUBLICACIONES = 183L;
  Long OTROS_GASTOS_RUBROS_BIBLIOGRAFIA = 229L;

  String TIPO_INVESTIGADOR_TRABAJO_GRADO = "TIPO_INVESTIGADOR_TRABAJO_GRADO";

  Long TIPO_INVESTIGADOR_TRABAJO_GRADO_INVESTIGADOR_PRINCIPAL = 186L;
  Long TIPO_INVESTIGADOR_TRABAJO_GRADO_CO_INVESTIGADOR = 187L;
  Long TIPO_INVESTIGADOR_TRABAJO_GRADO_ASESOR_METODOLOGICO = 188L;
  Long TIPO_INVESTIGADOR_TRABAJO_GRADO_ASESOR_TEMATICO = 189L;

  String TIPO_VINCULACION_TRABAJO_GRADO = "TIPO_VINCULACION_TRABAJO_GRADO";
  Long TIPO_VINCULACION_TRABAJO_GRADO_UNIFORMADO = 190L;
  Long TIPO_VINCULACION_TRABAJO_GRADO_NO_UNIFORMADO = 191L;
  Long TIPO_VINCULACION_TRABAJO_GRADO_CONTRATO = 192L;
  Long TIPO_VINCULACION_TRABAJO_GRADO_EXTERNO = 193L;

  Long TIPO_INVESTIGADOR_PROY_GRADO_INVESTIGADOR = 194L;
  Long TIPO_INVESTIGADOR_PROY_GRADO_ASESOR = 195L;

  String TIPO_ESTADO_ENSAYO_CRITICO = "TIPO_ESTADO_ENSAYO_CRITICO";
  Long TIPO_ESTADO_ENSAYO_CRITICO_EN_ELABORACION = 196L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_RECIBIDO = 197L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_LEIDO = 198L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_EVALUADO = 199L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_NO_APROBADO_UNIDAD = 200L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_ENVIADO_VICIN = 201L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_LEIDO_VICIN = 202L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_EVALUADO_VICIN = 203L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_GANADOR = 204L;
  Long TIPO_ESTADO_ENSAYO_CRITICO_NO_APROBADO = 205L;

  String TIPO_DOCUMENTO_TRABAJO_GRADO = "TIPO_DOCUMENTO_TRABAJO_GRADO";
  Long TIPO_DOCUMENTO_TRABAJO_GRADO_INFORME_DE_AVANCE = 206L;
  Long TIPO_DOCUMENTO_TRABAJO_GRADO_TRABAJO_DE_GRADO_INFORME_FINAL = 207L;
  Long TIPO_DOCUMENTO_TRABAJO_GRADO_ACTA_DE_SUSTENTACIÓN = 208L;

  String TIPO_ESTADO_EVALUACION_UNIDAD_ENSAYO = "TIPO_ESTADO_EVALUACION_UNIDAD_ENSAYO";
  Long TIPO_ESTADO_EVALUACION_UNIDAD_ENSAYO_NO_APROBADO = 212L;
  Long TIPO_ESTADO_EVALUACION_UNIDAD_ENSAYO_APROBADO = 213L;

  String TIPO_ESTADO_VINCULACION_INVESTIGADOR = "TIPO_ESTADO_VINCULACION_INVESTIGADOR";
  String TIPO_CARACTERISTICAS_INVESTIGADOR = "TIPO_CARACTERISTICAS_INVESTIGADOR";

  Long ESTADO_VINCULACION_INVESTIGADOR_VINCULADO = 214L;
  Long ESTADO_VINCULACION_INVESTIGADOR_NO_VINCULADO = 215L;

  //String TIPO_CRITERIO_EVAL
  String TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO = "TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO";
  Long TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO_VIRTUAL = 218L;
  Long TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO_PRESENCIAL = 219L;
  Long TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO_TELEFONICA = 220L;
  Long TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO_OTROS = 221L;

  Long TIPO_CARACTERISTICAS_INVESTIGADOR_ID_PUBLICACIONES = 216L;
  Long TIPO_CARACTERISTICAS_INVESTIGADOR_ID_INVESTIGACIONES = 217L;

  String TIPO_ESTADO_EVALUACION_VICIN_ENSAYO = "TIPO_ESTADO_EVALUACION_VICIN_ENSAYO";
  Long TIPO_ESTADO_EVALUACION_VICIN_ENSAYO_GANADOR = 223L;
  Long TIPO_ESTADO_EVALUACION_VICIN_ENSAYO_NO_APROBADO = 222L;

  String TIPO_AUTOR_COMENTARIO_EVALUACION_ENSAYO = "TIPO_AUTOR_COMENTARIO_EVALUACION_ENSAYO";
  Long TIPO_AUTOR_COMENTARIO_EVALUACION_ENSAYO_VICIN = 224L;
  Long TIPO_AUTOR_COMENTARIO_EVALUACION_ENSAYO_JEFE_UNIDAD = 225L;

  Long TIPO_COMPROMISO_IMPLEMENTACION_PLAN_DE_TRABAJO = 226L;
  Long TIPO_COMPROMISO_IMPLEMENTACION_INFORME_AVANCE = 227L;
  Long TIPO_COMPROMISO_IMPLEMENTACION_INFORME_FINAL = 228L;

  Long TIPO_ESTADO_RESULTADO_COMPROMISO_PROYECTO_ACEPTADO = 233L;
  Long TIPO_ESTADO_RESULTADO_COMPROMISO_PROYECTO_NO_ACEPTADO = 234L;

  Long RESULTADO_VALIDACION_PROYECTOS_OK = 0L;
  Long RESULTADO_VALIDACION_PROYECTOS_CODIGO_INEXISTENTE = 1L;
  Long RESULTADO_VALIDACION_PROYECTOS_NO_EVALUADOS = 2L;

  String ESTADO_IMPLEMENTACION_PROYECTO = "ESTADO_IMPLEMENTACION_PROYECTO";
  Long ESTADO_IMPLEMENTACION_PROYECTO_INICIANDO_IMPLEMENTACION = 209L;
  Long ESTADO_IMPLEMENTACION_PROYECTO_EN_PROCESO = 210L;
  Long ESTADO_IMPLEMENTACION_PROYECTO_IMPLEMENTADA = 211L;

  String TIPO_TIPOS_DE_PROYECTO = "TIPO_TIPOS_DE_PROYECTO";
  Long TIPO_TIPOS_DE_PROYECTO_INVESTIGACIONES_INSTITUCIONALES = 235L;
  Long TIPO_TIPOS_DE_PROYECTO_TRABAJOS_DE_GRADO = 236L;
  Long TIPO_TIPOS_DE_PROYECTO_PARA_FINANCIACION = 237L;

  String TIPO_ORIGENES_PROYECTO = "TIPO_ORIGENES_PROYECTO";
  Long TIPO_ORIGENES_PROYECTO_BANCO_DE_NECESIDADES = 238L;
  Long TIPO_ORIGENES_PROYECTO_PROPUESTA_DE_NECESIDADES = 239L;
  Long TIPO_ORIGENES_PROYECTO_CONVOCATORIA = 240L;
  Long TIPO_ORIGENES_PROYECTO_TRABAJO_DE_GRADO = 241L;

  String TIPO_FORMAS_DE_VER = "TIPO_FORMAS_DE_VER";
  Long TIPO_FORMAS_DE_VER_UNO_A_UNO = 242L;
  Long TIPO_FORMAS_DE_VER_TOTALES_POR_UNIDAD = 243L;

  String TIPO_CRITERIO_EVALUACION_ADMINISTRAR = "TIPO_CRITERIO_EVALUACION_ADMINISTRAR";
  Long ID_TIPO_CRITERIO_CONVOCATORIA_FINANCIACION = 245L;
  Long ID_TIPO_CRITERIO_CONVOCATORIA_ENSAYO = 246L;
  Long ID_TIPO_CRITERIO_EVALUACION_PROYECTO = 247L;

  Long ID_TIPO_RESULTADO_RETROALIMENTACION_COMPROMISO_REQUIERE_CORRECCION = 248L;
  Long ID_TIPO_RESULTADO_RETROALIMENTACION_COMPROMISO_NO_REQUIERE_CORRECCION = 249L;

  String TIPO_DE_PROYECTO = "TIPO_DE_PROYECTO";
  Long TIPO_DE_PROYECTO_DE_CONVOCATORIA_DE_FINANCIACION = 250L;
  Long TIPO_DE_PROYECTO_PROYECTOS_INSTITUCIONALES = 251L;

  String TIPO_COMPROMISO_CORRECCION = "TIPO_COMPROMISO_CORRECCION";
  Long TIPO_COMPROMISO_CORRECCION_PENDIENTE_CORRECCION = 252L;

  String TIPO_RELACION_SEMILLERO = "TIPO_RELACION_SEMILLERO";
  Long TIPO_RELACION_SEMILLERO_ASESOR_METODOLOGICO = 253L;
  Long TIPO_RELACION_SEMILLERO_COORDINADOR = 254L;
  Long TIPO_RELACION_SEMILLERO_INTEGRANTE_SEMILLERO = 255L;

  String TIPO_VINCULACION_SEMILLERO = "TIPO_VINCULACION_SEMILLERO";
  Long TIPO_VINCULACION_SEMILLERO_DOCENTE = 256L;
  Long TIPO_VINCULACION_SEMILLERO_ADMINISTRATIVO = 257L;
  Long TIPO_VINCULACION_SEMILLERO_UNIFORMADO = 258L;
  Long TIPO_VINCULACION_SEMILLERO_NO_UNIFORMADO = 259L;
  Long TIPO_VINCULACION_SEMILLERO_CONTRATO = 260L;

  String TIPO_DIAS_SEMANA = "TIPO_DIAS_SEMANA";
  Long TIPO_DIAS_SEMANA_LUNES = 261L;
  Long TIPO_DIAS_SEMANA_MARTES = 262L;
  Long TIPO_DIAS_SEMANA_MIERCOLES = 263L;
  Long TIPO_DIAS_SEMANA_JUEVES = 264L;
  Long TIPO_DIAS_SEMANA_VIERNES = 265L;
  Long TIPO_DIAS_SEMANA_SABADO = 266L;

  String TIPO_MODALIDAD_PARTICIPACION_SEMILLERO = "TIPO_MODALIDAD_PARTICIPACION_SEMILLERO";
  Long TIPO_MODALIDAD_PARTICIPACION_SEMILLERO_PONENTES = 267L;
  Long TIPO_MODALIDAD_PARTICIPACION_SEMILLERO_ASISTENTES = 268L;

  Long TIPO_UNIDAD_POLICIAL_ESCUELAS = 1L;
  Long TIPO_UNIDAD_POLICIAL_OTROS = 2L;

  Long TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL_REALIZADA = 269L;
  Long TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL_NO_CUMPLIDA = 270L;
  Long TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL_PARCIALMENTE_REALIZADA = 271L;

  String TIPO_EVENTO_INVESTIGA = "TIPO_EVENTO_INVESTIGA";
  Long TIPO_EVENTO_INVESTIGA_ENCUENTRO_INVESTIGA = 272L;
  Long TIPO_EVENTO_INVESTIGA_FERIA_NACIONAL = 273L;
  Long TIPO_EVENTO_INVESTIGA_FERIA_INTERNACIONAL = 274L;

  String CRITERIO_SEMILLERO_UNIDAD_POLICIAL = "unidad-policial";
  String CRITERIO_SEMILLERO_PALABRA_CLAVE = "palabra-clave";
  String CRITERIO_SEMILLERO_ESTADO_SEMILLERO = "estado-semillero";
  String CRITERIO_SEMILLERO_TRABAJO_INDEPENDIENTE = "trabajo-independiente";
  String CRITERIO_SEMILLERO_ANIO_CREACION = "anio-creacion";

  String CONTENIDO_ADJUNTO_MAIL = "contenido-adjunto-mail";
  String NOMBRE_ADJUNTO_MAIL = "nombre-adjunto-mail";

  String TIPO_REGISTRO_PERIODO_NECESIDAD = "NECESIDAD";
  String TIPO_REGISTRO_PERIODO_CONVOCATORIA = "CONVOCATORIA";

  String VALIDACIONES_NECESIDADES_ERROR_FORMULACION_REQUERIDA = "validacion_necesidades_error_formulacion_requerida";
  String VALIDACIONES_NECESIDADES_ERROR_FORMULACION_MULTIPLE = "validacion_necesidades_error_formulacion_multiple";
  String VALIDACIONES_NECESIDADES_ERROR_INFROME_AVANCE_REQUERIDO = "validacion_necesidades_error_informe_avance_requerido";
  String VALIDACIONES_NECESIDADES_ERROR_INFORME_FINAL_REQUERIDO = "validacion_necesidades_error_informe_final_requerido";
  String VALIDACIONES_NECESIDADES_ERROR_INFORME_FINAL_MULTIPLE = "validacion_necesidades_error_informe_final_multiple";

  String VALIDACIONES_CONVOCATORIAS_ERROR_FORMULACION_MULTIPLE = "validacion_convocatorias_error_formulacion_multiple";
  String VALIDACIONES_CONVOCATORIAS_ERROR_INFORME_AVANCE_REQUERIDO = "validacion_convocatorias_error_informe_avance_requerido";
  String VALIDACIONES_CONVOCATORIAS_ERROR_INFORME_FINAL_REQUERIDO = "validacion_convocatorias_error_informe_final_requerido";
  String VALIDACIONES_CONVOCATORIAS_ERROR_INFORME_FINAL_MULTIPLE = "validacion_convocatorias_error_informe_final_multiple";

  String VALIDACIONES_CONVOCATORIAS_ERROR_NO_COMPROMISOS = "validacion_convocatorias_error_no_compromisos";
  String VALIDACIONES_NECESIDADES_ERROR_NO_COMPROMISOS = "validacion_necesidades_error_no_compromisos";

  String CRITERIO_PROPUESTAS_PROYECTO_INV_AREA = "area";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_LINEA = "linea";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_PALABRA_CLAVE = "palabra-clave";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_ESTADO = "estado";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_UNIDAD_POLICIAL = "unidad-policial";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_FECHA_INICIAL = "fecha-inicial-presentacion";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_FECHA_FINAL = "fecha-final-presentacion";
  String CRITERIO_PROPUESTAS_PROYECTO_INV_CONVOCATORIA = "convocatoria";

  String CRITERIO_CONVOCATORIAS_TIPO_CONVOCATORIA = "tipo-convocatoria";
  String CRITERIO_CONVOCATORIAS_CONSECUTIVO = "consecutivo";
  String CRITERIO_CONVOCATORIAS_PALABRA_CLAVE = "palabra-clave";
  String CRITERIO_CONVOCATORIAS_ESTADO_CONVOCATORIA = "estado-convocatoria";
  String CRITERIO_CONVOCATORIAS_FECHA_INICIAL = "fecha-inicial-convocatoria";
  String CRITERIO_CONVOCATORIAS_FECHA_FINAL = "fecha-final-convocatoria";

  String TIPO_PARAMETROS_SISTEMA = "TIPO_PARAMETROS_SISTEMA";

  String CONFIG_CONEXION_BD_GENERACION_REPORTE = "CONFIG_CONEXION_BD_GENERACION_REPORTE";

  String PATH_FILES_VIECO = "PATH_FILES_VIECO";

}
