CREATE TABLE SIEDU_TIPO_DOMINIO
  (
    id_tipo_dominio     NUMBER (3) NOT NULL ,
    nombre              VARCHAR2 (100) NOT NULL ,
    descripcion         VARCHAR2 (500)
  ) ;

ALTER TABLE SIEDU_TIPO_DOMINIO ADD CONSTRAINT SIEDU_ID_TIPO_DOMINIO_PK PRIMARY KEY ( id_tipo_dominio ) ;
ALTER TABLE SIEDU_TIPO_DOMINIO ADD CONSTRAINT SIEDU_TIPO_DOMINIO_UK UNIQUE ( nombre ) ;

CREATE SEQUENCE SIEDU_TIPO_DOMINIO_SEQ_GEN;
