CREATE TABLE SIEDU_DOMINIO
  (
    id_dominio          NUMBER (4) NOT NULL ,
    id_tipo_dominio     NUMBER (3) NOT NULL ,
    nombre       		VARCHAR2 (100) NOT NULL ,
    descripcion 		VARCHAR2 (500) ,
    vigente             VARCHAR2 (5)
  );

ALTER TABLE SIEDU_DOMINIO ADD CONSTRAINT SIEDU_DOMINIO_PK PRIMARY KEY ( id_dominio ) ;
ALTER TABLE SIEDU_DOMINIO ADD CONSTRAINT SIEDU_DOMINIO_UK UNIQUE ( id_tipo_dominio , nombre ) ;
ALTER TABLE SIEDU_DOMINIO ADD CONSTRAINT SIEDU_TIPODOM_DOMINIO_FK FOREIGN KEY ( id_tipo_dominio ) REFERENCES SIEDU_TIPO_DOMINIO ( id_tipo_dominio ) ;

CREATE SEQUENCE SIEDU_DOMINIO_SEQ_GEN;
