--------------------------------------------------------
-- Archivo creado  - martes-marzo-15-2016   
--------------------------------------------------------
REM INSERTING into USR_DISIGAC2.SIEDU_TIPO_DOMINIO
SET DEFINE OFF;
Insert into USR_DISIGAC2.SIEDU_TIPO_DOMINIO (ID_TIPO_DOMINIO,DESCRIPCION,DEFINICION) values ('1','VIGENCIA','Vigencias para el PAE');
Insert into USR_DISIGAC2.SIEDU_TIPO_DOMINIO (ID_TIPO_DOMINIO,DESCRIPCION,DEFINICION) values ('2','TIPO DOCUMENTO','Tipos de documentos');
REM INSERTING into USR_DISIGAC2.SIEDU_DOMINIO
SET DEFINE OFF;
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('1','1','2010','true');
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('2','1','2011','true');
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('3','1','2012','true');
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('4','1','2013','true');
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('5','1','2014','true');
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('6','1','2015','true');
Insert into USR_DISIGAC2.SIEDU_DOMINIO (ID_DOMINIO,ID_TIPO_DOMINIO,DESCRIPCION,VIGENTE) values ('7','1','2016','true');
