insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68300,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
10								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68301,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
12								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68302,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68303,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68304,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68305,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68306,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17406,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68307,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 

insert into siedu_necesidad_e (
ENEC_ENEC
,ENEC_VIGENCIA
,ENEC_UDE_FUERZA_REGION
,ENEC_UDE_REGION
,ENEC_UDE_FUERZA_UFISI
,ENEC_UDE_UFISI
,ENEC_UDE_FUERZA_UDEPE
,ENEC_UDE_UDEPE
,ENEC_FUERZA_CARRERA
,ENEC_ID_CARRERA
,ENEC_ORIGEN
,ENEC_NRO
) values (
SIEDU_NECESIDAD_E_SEQ.nextval,	-- ENEC_ENEC
'2016',							-- ,ENEC_VIGENCIA
6,								-- ,ENEC_UDE_FUERZA_REGION
17405,							-- ,ENEC_UDE_REGION
6,								-- ,ENEC_UDE_FUERZA_UFISI
17407,							-- ,ENEC_UDE_UFISI
6,								-- ,ENEC_UDE_FUERZA_UDEPE
17407,							-- ,ENEC_UDE_UDEPE
6,								-- ,ENEC_FUERZA_CARRERA
68307,							-- ,ENEC_ID_CARRERA
'DITAH',						-- ,ENEC_ORIGEN
11								-- ,ENEC_NRO
); 