CREATE OR REPLACE VIEW FORMACION_INVEST_INT_EXT (NUMERO_IDENTIFICACION, NIVEL_FORMACION, AREA_SABER, TITULO_OBTENIDO, FECHA_FINALIZACION) AS 
  (SELECT 
INVESTIGADOR.NUMERO_IDENTIFICACION,
CONSTANTES.VALOR NIVEL_FORMACION,
constantes2.VALOR AREA_SABER,
TITULO_OBTENIDO,
FECHA_FINALIZACION
FROM
FORMACION_INVESTIGADOR,
INVESTIGADOR,
CONSTANTES,
CONSTANTES constantes2
WHERE
INVESTIGADOR.ID_INVESTIGADOR = FORMACION_INVESTIGADOR.ID_INVESTIGADOR
AND CONSTANTES.ID_CONSTANTES = ID_NIVEL_FORMACION
AND constantes2.ID_CONSTANTES = ID_AREA_SABER
UNION
SELECT
TO_CHAR(IDENTIFICACION),
NIVEL_ACADEMICO,
NULL,
TITULO,
FECHA_TERMINO
FROM
NIVACA_VICIN_DINAE)
ORDER BY FECHA_FINALIZACION DESC;

ALTER TABLE ENSAYO_CRITICO ADD IDENTIFICA_EVALUA_CUCO8 VARCHAR2(100);
ALTER TABLE ENSAYO_CRITICO ADD NOMBRE_APELLIDO_EVALUA_CUCO8 VARCHAR2(100);

ALTER TABLE ENSAYO_CRITICO ADD IDENTIFICA_EVALUA_CUCO10 VARCHAR2(100);
ALTER TABLE ENSAYO_CRITICO ADD NOMBRE_APELLIDO_EVALUA_CUCO10 VARCHAR2(100);


CREATE TABLE INFO_ADICIONAL_PERSONA_SIAT
  (
    IDENTIFICACION VARCHAR2(50) NOT NULL,
    PROFESOR       VARCHAR2(1)
  );