drop table FUENTE_PROYECTO cascade constraint;
CREATE TABLE FUENTE_PROYECTO
  (
    ID_FUENTE_PROYECTO NUMBER NOT NULL ENABLE,
    ID_TIPO_FUENTE     NUMBER NOT NULL ENABLE,
    ID_PROYECTO        NUMBER NOT NULL ENABLE,
    ID_USUARIO_ROL     NUMBER NOT NULL ENABLE,
    FECHA_REGISTRO TIMESTAMP (6) NOT NULL ENABLE,
    NOMBRE_FUENTE VARCHAR2(100 BYTE) NOT NULL ENABLE,
    CONSTRAINT FUENTE_PROYECTO_PK PRIMARY KEY (ID_FUENTE_PROYECTO),
    CONSTRAINT FUENTE_PROYECTO_PROYECTO_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO) ENABLE,
    CONSTRAINT TIPO_FUENTE_PROYECTO_FK FOREIGN KEY (ID_FUENTE_PROYECTO) REFERENCES CONSTANTES (ID_CONSTANTES) ENABLE,
    CONSTRAINT FUENTEUSUARIO_USUARIOROL_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) ENABLE
  );

ALTER TABLE SEMILLERO_INVESTIGACION ADD CONSTRAINT FK_UNI_POLI_Y_UNIDAD_SEMILLER FOREIGN KEY (ID_UNIDAD_POLICIAL) REFERENCES UNIDAD_POLICIAL (ID_UNIDAD_POLICIAL);
--ALTER TABLE SEMILLERO_INVESTIGACION ADD CONSTRAINT SEMILLERO_INVESTIGACION_PK PRIMARY KEY ( ID_SEMILLERO );

drop table CRITERIO_EVALUACION cascade constraint;
-- CREATE TABLE CRITERIO_EVALUACION
--   (
--     ID_CRITERIO_EVALUACION NUMBER NOT NULL, 
--     NOMBRE_CRITERIO        VARCHAR2(40),
--     DESCRIPCION_CRITERIO   VARCHAR2(256),
--     VALOR                  NUMBER(5,2),
--     ID_TIPO             NUMBER NOT NULL ,
--     ID_ESTADO        NUMBER NOT NULL,
--     CONSTRAINT CRITERIO_EVALUACION_PK PRIMARY KEY (ID_CRITERIO_EVALUACION),
--     CONSTRAINT TIPO_CONSTANTE_FK FOREIGN KEY (ID_TIPO) REFERENCES CONSTANTES (ID_CONSTANTES),
--     CONSTRAINT ESTADO_CONSTANTE_FK FOREIGN KEY (ID_ESTADO) REFERENCES CONSTANTES (ID_CONSTANTES)
--   );

CREATE TABLE CRITERIO_EVALUACION
  (
    ID_CRITERIO_EVALUACION NUMBER NOT NULL, 
    NOMBRE_CRITERIO        VARCHAR2(40),
    DESCRIPCION_CRITERIO   VARCHAR2(256),
    VALOR                  NUMBER(5,2),
    TIPO          VARCHAR2(50) NOT NULL ,
    ESTADO        VARCHAR2(50) NULL,
    CONSTRAINT CRITERIO_EVALUACION_PK PRIMARY KEY (ID_CRITERIO_EVALUACION)
  );

CREATE SEQUENCE SEC_CRITERIO_EVALUACION
  START WITH 1
  INCREMENT by 1
  MINVALUE 1
;

ALTER TABLE EVALUACION_PROYECTO ADD CONSTRAINT CRITERIO_PROYECTO_FK FOREIGN KEY (ID_CRITERIO_EVALUACION) REFERENCES CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION);

CREATE SEQUENCE SEC_EVALUACION_PROYECTO
  START WITH 1
  INCREMENT by 1
  MINVALUE 1
;

ALTER TABLE COMENTARIO_PROYECTO ADD CONSTRAINT ITEM_CONSTANTES_FK FOREIGN KEY (ID_ITEM) REFERENCES CONSTANTES (ID_CONSTANTES);
ALTER TABLE COMENTARIO_PROYECTO ADD COMENTARIO_ENVIAR CHAR(1);

CREATE SEQUENCE SEC_COMENTARIO_PROYECTO
  START WITH 1
  INCREMENT by 1
  MINVALUE 1
;


ALTER TABLE PROYECTO ADD ESTADO_TEMPORAL_FINANCIA VARCHAR2(20);
ALTER TABLE PROYECTO ADD VALOR_FINANCIAR NUMBER(11,2);

ALTER TABLE COMENTARIO_PROYECTO ADD IDENTIFICACION VARCHAR2(100);
ALTER TABLE COMENTARIO_PROYECTO ADD NOMBRE_COMPLETO VARCHAR2(200);

Insert into CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION,NOMBRE_CRITERIO,DESCRIPCION_CRITERIO,VALOR,TIPO,ESTADO) values ('1','Solución al problema de investigación','Solución al problema de investigación','30','FINANCIACION','ACTIVO');
Insert into CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION,NOMBRE_CRITERIO,DESCRIPCION_CRITERIO,VALOR,TIPO,ESTADO) values ('2','Cumplimiento de objetivos','Cumplimiento de objetivos','40','FINANCIACION','ACTIVO');
Insert into CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION,NOMBRE_CRITERIO,DESCRIPCION_CRITERIO,VALOR,TIPO,ESTADO) values ('3','Claridad conceptual','Claridad conceptual','30','FINANCIACION','ACTIVO');

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('88','TIPO_ITEM_COMENTARIO_REVISION_PROYECTO','Objetivo','Objetivo');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('89','TIPO_ITEM_COMENTARIO_REVISION_PROYECTO','Planteamiento del proyecto','Planteamiento del proyecto');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('90','TIPO_ITEM_COMENTARIO_REVISION_PROYECTO','Indicadores','Indicadores');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('91','TIPO_ITEM_COMENTARIO_REVISION_PROYECTO','Otro','Otro');

commit;