ALTER TABLE PROYECTO  MODIFY (NRO_ACTA_APROB_COMITE VARCHAR(20));

UPDATE CONSTANTES SET CODIGO = 'Policía DINAE', VALOR = 'Policía DINAE-Interna' WHERE ID_CONSTANTES = 99;
UPDATE FUENTE_PROYECTO SET NOMBRE_FUENTE = 'Policía DINAE' WHERE NOMBRE_FUENTE = 'VICIN';

ALTER TABLE PLAN_TRABAJO_IMPLEMENTACION  
MODIFY (OBJETIVOS_ESPECIFICOS VARCHAR2(1000 BYTE) );

ALTER TABLE PROYECTO  MODIFY (NRO_ACTA_APROB_COMITE VARCHAR(20));
CREATE SEQUENCE  SEC_USUARIO_UNIDAD_POLICIAL  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--Scripts para modificar los valores iniciales de las secuencias SEC_USUARIO_ROL y SEC_USUARIO_UNIDAD_POLICIAL
			
SET SERVEROUTPUT ON SIZE 1000000
DECLARE
	max_id_usuario_rol NUMBER;
	temp_seq NUMBER;
BEGIN
	SELECT MAX(ID_USUARIO_ROL)  INTO max_id_usuario_rol FROM USUARIO_ROL;
	EXECUTE IMMEDIATE 'ALTER SEQUENCE SEC_USUARIO_ROL INCREMENT BY ' || max_id_usuario_rol;
	SELECT SEC_USUARIO_ROL.NEXTVAL INTO temp_seq FROM dual;
	
	EXECUTE IMMEDIATE 'ALTER SEQUENCE SEC_USUARIO_ROL INCREMENT BY 1';
	DBMS_OUTPUT.put_line('Executed "ALTER SEQUENCE SEC_USUARIO_ROL INCREMENT BY ' || max_id_usuario_rol || '"');
END;


SET SERVEROUTPUT ON SIZE 1000000
DECLARE
	max_id_usuario_unidad_policial NUMBER;
	temp_seq NUMBER;
BEGIN
	SELECT MAX(ID_USUARIO_UNIDAD_POLICIAL)  INTO max_id_usuario_unidad_policial FROM USUARIO_UNIDAD_POLICIAL;
	EXECUTE IMMEDIATE 'ALTER SEQUENCE SEC_USUARIO_UNIDAD_POLICIAL INCREMENT BY ' || max_id_usuario_unidad_policial;
	SELECT SEC_USUARIO_UNIDAD_POLICIAL.NEXTVAL INTO temp_seq FROM dual;
	
	EXECUTE IMMEDIATE 'ALTER SEQUENCE SEC_USUARIO_UNIDAD_POLICIAL INCREMENT BY 1';
	DBMS_OUTPUT.put_line('Executed "ALTER SEQUENCE SEC_USUARIO_UNIDAD_POLICIAL INCREMENT BY ' || max_id_usuario_unidad_policial || '"');
END;


--insert into CORREO_PARAMETRIZA select cp.CODIGO,cp.ASUNTO,cp.TEXTO,cp.FORMATO from dinae1_2iteracion_final.CORREO_PARAMETRIZA cp where cp.CODIGO = 'CU_PR_25_GRUPO_INVESTIGACION'

alter table COMENTARIO_COMPROMISO_PROYECTO add ID_ITEM NUMBER;
alter table COMENTARIO_COMPROMISO_PROYECTO add CONSTRAINT ITEM_COMEN_COMP_PRO_CONSTAN_FK FOREIGN KEY (ID_ITEM) REFERENCES CONSTANTES (ID_CONSTANTES);
alter table COMENTARIO_COMPROMISO_PROYECTO add COMENTARIO_ENVIAR CHAR(1);
