DROP TABLE FORMACION_INVESTIGADOR CASCADE CONSTRAINTS;
CREATE TABLE FORMACION_INVESTIGADOR
  (
    ID_FORMACION_INV   NUMBER NOT NULL ,
    ID_INVESTIGADOR    NUMBER NOT NULL ,
    ID_NIVEL_FORMACION NUMBER NOT NULL ,
    ID_AREA_SABER      NUMBER,
    TITULO_OBTENIDO    VARCHAR2(100) NOT NULL ,
    FECHA_FINALIZACION DATE,
    CONSTRAINT FORMACION_INVESTIGADOR_PK PRIMARY KEY (ID_FORMACION_INV),
    CONSTRAINT FORMACION_AREA_SABER_FK FOREIGN KEY (ID_AREA_SABER) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT FORMACION_INVESTIGADOR_FK FOREIGN KEY (ID_INVESTIGADOR) REFERENCES INVESTIGADOR (ID_INVESTIGADOR) ,
    CONSTRAINT FORMACION_NIVELFORMACION_FK FOREIGN KEY (ID_NIVEL_FORMACION) REFERENCES CONSTANTES (ID_CONSTANTES) 
  );

CREATE SEQUENCE SEC_TIPO_GASTO_EVENTO
  INCREMENT by 1
  MINVALUE 1
;
 CREATE SEQUENCE SEC_INVESTIGACIONES_DESARROLLA
  INCREMENT by 1
  MINVALUE 1
;

 CREATE SEQUENCE SEC_INVESTIGADOR
  INCREMENT by 1
  MINVALUE 1
;


CREATE TABLE INVESTI_DESARROL_INVESTTIGADOR 
(
  ID_INVESTI_DESARROL_INVESTTIGA NUMBER NOT NULL, 
  ID_INVESTIGADOR NUMBER NOT NULL,
  TITULO_INVESTIGACION VARCHAR2(250) NOT NULL, 
  RESUMEN VARCHAR2(512) NOT NULL, 
  INSTITUCION VARCHAR2(250) NOT NULL, 
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NOT NULL,
  FECHA_INGRESO_REGISTRO TIMESTAMP NOT NULL,
  FECHA_MODIFICA_REGISTRO TIMESTAMP,
  CONSTRAINT INVESTIGACIONES_DESARROLLA_PK PRIMARY KEY (ID_INVESTI_DESARROL_INVESTTIGA),  
  CONSTRAINT INVESTIGADOR_INVES_DESARRO_FK FOREIGN KEY (ID_INVESTIGADOR) REFERENCES INVESTIGADOR (ID_INVESTIGADOR) 
);


CREATE TABLE EVIDENCIA_PROYECTO
  (
    ID_EVIDENCIA_PROYECTO      NUMBER NOT NULL ,
    ID_TIPO_ARCHIVO             NUMBER NOT NULL ,
    ID_PROYECTO                 NUMBER NOT NULL,
    DESCRIPCION          	VARCHAR2(512 ) NOT NULL ,
    NOMBRE_ARCHIVO_USUARIO      VARCHAR2(100 ),
    NOMBRE_ARCHIVO_FISICO       VARCHAR2(100 ),
    FECHA_INGRESO_REGISTRO TIMESTAMP NOT NULL,
    FECHA_MODIFICA_REGISTRO TIMESTAMP,
    CONSTRAINT ENVIDENCIA_PROYECTO_FK PRIMARY KEY (ID_EVIDENCIA_PROYECTO),
    CONSTRAINT FK_TIPO_ARCHI_CONSTANTE FOREIGN KEY (ID_TIPO_ARCHIVO) REFERENCES CONSTANTES (ID_CONSTANTES),
    CONSTRAINT ID_PROYECTO_EVIEN_PROY_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
  );
  
 CREATE SEQUENCE SEC_EVIDENCIA_PROYECTO
  INCREMENT by 1
  MINVALUE 1
;

drop table INVESTIGADOR cascade constraints;
CREATE TABLE INVESTIGADOR
  (
    ID_INVESTIGADOR          NUMBER NOT NULL ,
    NUMERO_IDENTIFICACION    VARCHAR2(20) NOT NULL ,
    CODIGO_CIUDAD_EXPEDICION VARCHAR2(6),
    NOMBRE_CIUDAD_EXPEDICION VARCHAR2(100),
    NOMBRES                  VARCHAR2(100) NOT NULL ,
    APELLIDOS                VARCHAR2(100) NOT NULL ,
    CORREO_ELECTRONICO       VARCHAR2(100) NOT NULL ,
    TELEFONO                 VARCHAR2(20) NOT NULL ,
    DIRECCION                VARCHAR2(100) NOT NULL ,
    CODIGO_DEPTO_RESIDENCIA  VARCHAR2(6) NOT NULL ,
    NOMBRE_DEPTO_RESIDENCIA  VARCHAR2(100) NOT NULL ,
    CODIGO_CIUDAD_RESIDENCIA VARCHAR2(6) NOT NULL ,
    NOMBRE_CIUDAD_RESIDENCIA VARCHAR2(100),
    PROFESOR_POLICIAL        CHAR(1),
    TIPO_VINCULACION         NUMBER,
    FUNCION_INVESTIGADOR     VARCHAR2(512),
    CODIGO_DEPTO_EXPEDICION  VARCHAR2(6),
    NOMBRE_DEPTO_EXPEDICION  VARCHAR2(100),
    CONSTRAINT INVESTIGADOR_PK PRIMARY KEY (ID_INVESTIGADOR) ,
    CONSTRAINT INVESTIGADOR_UK1 UNIQUE (NUMERO_IDENTIFICACION) ,
    CONSTRAINT INVESTIGADOR_VINCULACION_FK FOREIGN KEY (TIPO_VINCULACION) REFERENCES CONSTANTES (ID_CONSTANTES) 
  );

DROP TABLE FORMACION_INVESTIGADOR CASCADE CONSTRAINTS;
CREATE TABLE FORMACION_INVESTIGADOR
  (
    ID_FORMACION_INV   NUMBER NOT NULL ,
    ID_INVESTIGADOR    NUMBER NOT NULL ,
    ID_NIVEL_FORMACION NUMBER NOT NULL ,
    ID_AREA_SABER      NUMBER,
    TITULO_OBTENIDO    VARCHAR2(100) NOT NULL ,
    FECHA_FINALIZACION DATE,
    CONSTRAINT FORMACION_INVESTIGADOR_PK PRIMARY KEY (ID_FORMACION_INV),
    CONSTRAINT FORMACION_AREA_SABER_FK FOREIGN KEY (ID_AREA_SABER) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT FORMACION_INVESTIGADOR_FK FOREIGN KEY (ID_INVESTIGADOR) REFERENCES INVESTIGADOR (ID_INVESTIGADOR) ,
    CONSTRAINT FORMACION_NIVELFORMACION_FK FOREIGN KEY (ID_NIVEL_FORMACION) REFERENCES CONSTANTES (ID_CONSTANTES) 
  );

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('135','TIPO_GASTO_EVENTO_RELACIONADO','Promoción','Promoción');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('136','TIPO_GASTO_EVENTO_RELACIONADO','Organización','Organización');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('137','TIPO_GASTO_EVENTO_RELACIONADO','Sede y logística','Sede y logística');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('138','TIPO_GASTO_EVENTO_RELACIONADO','Comunicaciones','Comunicaciones');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('139','TIPO_GASTO_EVENTO_RELACIONADO','Pasajes y viáticos','Pasajes y viáticos');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('140','TIPO_GASTO_EVENTO_RELACIONADO','Transporte terrestre','Transporte terrestre');

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('100','ESTADO_COMPROMISO_PROYECTO','Pendiente','Pendiente');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('107','ESTADO_COMPROMISO_PROYECTO','Cumplido','Cumplido');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('108','ESTADO_COMPROMISO_PROYECTO','Correción Compromiso','Correción Compromiso');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('117','ESTADO_COMPROMISO_PROYECTO','En Revisión del Jefe','En Revisión del Jefe');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('118','ESTADO_COMPROMISO_PROYECTO','Enviado a VICIN','Enviado a VICIN');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('178','ESTADO_COMPROMISO_PROYECTO','En elaboración','En elaboración');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('179','ESTADO_COMPROMISO_PROYECTO','Aceptado','Aceptado');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('180','ESTADO_COMPROMISO_PROYECTO','Revisado','Revisado');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('181','ESTADO_COMPROMISO_PROYECTO','No aceptado','No aceptado');

UPDATE OPCION_MENU SET NOMBRE='Investigadores' WHERE ID_OPCION_MENU = 4;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('176','TIPO_EVIDENCIA_TIPO_ARCHIVO','Documento','Documento');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('177','TIPO_EVIDENCIA_TIPO_ARCHIVO','Fotografias','Fotografias');

DROP SEQUENCE SEC_VIAJES_PROYECTO;
CREATE SEQUENCE SEC_VIAJES_PROYECTO
  INCREMENT by 1
  MINVALUE 1
;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('182','OTROS_GASTOS_RUBROS','Gastos Administrativos','Gastos Administrativos');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('183','OTROS_GASTOS_RUBROS','Publicaciones','Publicaciones');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('184','OTROS_GASTOS_TIPO','Especie','Especie');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('185','OTROS_GASTOS_TIPO','Efectivo','Efectivo');

DROP SEQUENCE SEC_OTROS_GASTOS_PROYECTO;
CREATE SEQUENCE SEC_OTROS_GASTOS_PROYECTO
  INCREMENT by 1
  MINVALUE 1
;
CREATE SEQUENCE SEC_FORMACION_INVESTIGADOR
  INCREMENT by 1
  MINVALUE 1
;

DROP TABLE PROGRAMAS CASCADE CONSTRAINTS;
CREATE TABLE PROGRAMAS
  (
    ID_PROGRAMA NUMBER NOT NULL ,
    NOMBRE      VARCHAR2(100),
    ACTIVO      VARCHAR2(1),
    FECHA_REGISTRO DATE NOT NULL ,
    ID_USUARIO_ROL     NUMBER,
    ID_UNIDAD_POLICIAL NUMBER,
    CONSTRAINT PROGRAMAS_PK PRIMARY KEY (ID_PROGRAMA),
    CONSTRAINT ID_UNIDAD_UNIDAD_PROGRAMAS_FK FOREIGN KEY (ID_UNIDAD_POLICIAL) REFERENCES UNIDAD_POLICIAL (ID_UNIDAD_POLICIAL),
	CONSTRAINT ID_USUARIOROL_PROGRAMAS_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) 	
  );

DROP SEQUENCE SEC_PLAN_TRABAJO_IMP;
CREATE SEQUENCE SEC_PLAN_TRABAJO_IMP 
    INCREMENT by 1
    MINVALUE 1;

DROP SEQUENCE SEC_IMPLEMENTACION_PROYECTO;
CREATE SEQUENCE SEC_IMPLEMENTACION_PROYECTO 
    INCREMENT by 1
    MINVALUE 1;

DROP SEQUENCE SEC_PERSONAL_IMPLEMENTACION;
CREATE SEQUENCE SEC_PERSONAL_IMPLEMENTACION 
    INCREMENT by 1
    MINVALUE 1;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('141','INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Artículo en revista','Artículo en revista');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('142','INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Prototipo','Prototipo');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('143','INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Cartilla','Cartilla');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('144','INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Manual','Manual');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('145','INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Protocolo','Protocolo');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('146','INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Otro','Otro');
