CREATE TABLE REPORTE_CUCO10_RES_ENSAYOS_TMP (
  ID_REG NUMBER PRIMARY KEY,
  FECHA_REPORTE DATE DEFAULT SYSDATE NOT NULL,
  ID_ENSAYO NUMBER NOT NULL,
  ID_UNIDAD_POLICIAL NUMBER NOT NULL,
  UNIDAD_SIGLA_FISICA VARCHAR2(10) NOT NULL,
  IDENTIFICACION_USUARIO VARCHAR2(20) NOT NULL,  
  PUESTO NUMBER NOT NULL,
  NOMBRE_COMPLETO_USUARIO VARCHAR2(100) NOT NULL,
  GRADO_USUARIO VARCHAR2(20),
  TITULO_ENSAYO VARCHAR2(2000) NOT NULL,
  COMENTARIOS VARCHAR2(4000),
  VALOR_CRITERIO_1 NUMBER NOT NULL,
  VALOR_CRITERIO_2 NUMBER,
  VALOR_CRITERIO_3 NUMBER,
  VALOR_CRITERIO_4 NUMBER,
  VALOR_CRITERIO_5 NUMBER,
  VALOR_CRITERIO_6 NUMBER,
  VALOR_CRITERIO_7 NUMBER,
  VALOR_TOTAL NUMBER NOT NULL  
  
);

CREATE SEQUENCE SEC_REP_CUCO_10 INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999 MINVALUE 1;

create or replace PROCEDURE PRC_REPORTE_CUCO_10 (P_NUM_CONVOCA IN NUMBER) AS 

CURSOR ENSAYOS_CONVOCATORIA(P_CONVOCA NUMBER) IS
SELECT DISTINCT EC.ID_ENSAYO_CRITICO, UP.ID_UNIDAD_POLICIAL, UP.SIGLA_FISICA, EC.TITULO_ENSAYO, VF.IDENTIFICACION, VF.GRADO, VF.NOMBRE_COMPLETO, CP.COMENTARIO
FROM ENSAYO_CRITICO EC JOIN VISTA_FUNCIONARIO VF ON (EC.IDENTIFICACION = VF.IDENTIFICACION)
JOIN USUARIO_UNIDAD_POLICIAL UUP ON (VF.IDENTIFICACION = UUP.IDENTIFICADOR_USUARIO)
JOIN UNIDAD_POLICIAL UP ON (UUP.ID_UNIDAD_POLICIAL = UP.ID_UNIDAD_POLICIAL)
JOIN COMENTARIO_PROYECTO CP ON (EC.ID_ENSAYO_CRITICO = CP.ID_ENSAYO_CRITICO)
WHERE EC.ID_PERIODO = P_CONVOCA AND 
EC.ID_ESTADO_CUCO10 IN (204, 205) AND  -- Ganador y No Aprobado.
CP.ID_ENSAYO_CRITICO IS NOT NULL AND
CP.AUTOR_COMENTARIO = 224; -- AUTOR VICIN


CURSOR VALOR_CRITERIOS_ENSAYO(P_ID_ENSAYO NUMBER) IS
SELECT DISTINCT CE.ID_CRITERIO_EVALUACION, CE.NOMBRE_CRITERIO, CE.VALOR, EP.VALOR_CRITERIO, EP.VALOR_CRITERIO_VICIN, EP.ID_ENSAYO_CRITICO
FROM EVALUACION_PROYECTO EP JOIN CRITERIO_EVALUACION CE ON (EP.ID_CRITERIO_EVALUACION = CE.ID_CRITERIO_EVALUACION)
WHERE EP.ID_ENSAYO_CRITICO IS NOT NULL AND
EP.ID_ENSAYO_CRITICO = P_ID_ENSAYO AND 
EP.VALOR_CRITERIO_VICIN IS NOT NULL AND
CE.TIPO = 'ENSAYO_CRITICO' AND
CE.ESTADO = 'ACTIVO';

CURSOR TOMAR_ENSAYOS_REPORTE_TOTAL IS
SELECT ID_REG, PUESTO, VALOR_TOTAL
FROM REPORTE_CUCO10_RES_ENSAYOS_TMP
ORDER BY VALOR_TOTAL DESC;

V_TOTAL NUMBER;
V_PUESTO NUMBER;
V_CONT_REG NUMBER;
V_VALOR_CRITERIO_1 NUMBER := NULL;
V_VALOR_CRITERIO_2 NUMBER := NULL;
V_VALOR_CRITERIO_3 NUMBER := NULL;
V_VALOR_CRITERIO_4 NUMBER := NULL;
V_VALOR_CRITERIO_5 NUMBER := NULL;
V_VALOR_CRITERIO_6 NUMBER := NULL;
V_VALOR_CRITERIO_7 NUMBER := NULL;

BEGIN
  
  DELETE REPORTE_CUCO10_RES_ENSAYOS_TMP;
  COMMIT;
  
  V_CONT_REG := 1;
  
  FOR I IN ENSAYOS_CONVOCATORIA(P_NUM_CONVOCA) LOOP
    
    V_TOTAL := 0;      
              
        FOR J IN VALOR_CRITERIOS_ENSAYO(I.ID_ENSAYO_CRITICO) LOOP              
              V_TOTAL := V_TOTAL + J.VALOR_CRITERIO_VICIN;      
              
              IF (V_CONT_REG = 1) THEN
                V_VALOR_CRITERIO_1 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              IF (V_CONT_REG = 2) THEN
                V_VALOR_CRITERIO_2 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              IF (V_CONT_REG = 3) THEN
                V_VALOR_CRITERIO_3 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              IF (V_CONT_REG = 4) THEN
                V_VALOR_CRITERIO_4 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              IF (V_CONT_REG = 5) THEN
                V_VALOR_CRITERIO_5 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              IF (V_CONT_REG = 6) THEN
                V_VALOR_CRITERIO_6 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              IF (V_CONT_REG = 7) THEN
                V_VALOR_CRITERIO_7 := J.VALOR_CRITERIO_VICIN;
              END IF;
              
              V_CONT_REG := V_CONT_REG + 1;           
        END LOOP; 
        
        INSERT INTO REPORTE_CUCO10_RES_ENSAYOS_TMP (
          ID_REG,          
          ID_ENSAYO,
          ID_UNIDAD_POLICIAL,
          UNIDAD_SIGLA_FISICA,
          IDENTIFICACION_USUARIO,  
          PUESTO,
          NOMBRE_COMPLETO_USUARIO,
          GRADO_USUARIO,
          TITULO_ENSAYO,
          COMENTARIOS,
          VALOR_CRITERIO_1,
          VALOR_CRITERIO_2,
          VALOR_CRITERIO_3,
          VALOR_CRITERIO_4,
          VALOR_CRITERIO_5,
          VALOR_CRITERIO_6,
          VALOR_CRITERIO_7,
          VALOR_TOTAL)
        VALUES
        (SEC_REP_CUCO_10.NEXTVAL,
         I.ID_ENSAYO_CRITICO,
         I.ID_UNIDAD_POLICIAL,
         I.SIGLA_FISICA,
         I.IDENTIFICACION,
         1,
         I.NOMBRE_COMPLETO,
         I.GRADO,
         I.TITULO_ENSAYO,
         I.COMENTARIO,
         V_VALOR_CRITERIO_1,
         V_VALOR_CRITERIO_2,
         V_VALOR_CRITERIO_3,
         V_VALOR_CRITERIO_4,
         V_VALOR_CRITERIO_5,
         V_VALOR_CRITERIO_6,
         V_VALOR_CRITERIO_7,
         V_TOTAL         
         );
         
         COMMIT;
        
  END LOOP; 
  
  V_PUESTO := 1;
  
  -- CALCULAR PUESTOS ENSAYOS  
  FOR I IN TOMAR_ENSAYOS_REPORTE_TOTAL LOOP
      
      UPDATE REPORTE_CUCO10_RES_ENSAYOS_TMP
      SET PUESTO = V_PUESTO
      WHERE ID_REG = I.ID_REG;
      
      COMMIT;
      
      V_PUESTO := V_PUESTO + 1;
      
  END LOOP;
  
  
  
END PRC_REPORTE_CUCO_10;
/

-- CU_AD_02


ALTER TABLE GRUPO_INVESTIGACION 
ADD (ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL);

ALTER TABLE GRUPO_INVESTIGACION
ADD CONSTRAINT GRUPO_INVESTIGACION_CHK1 CHECK 
(ESTADO IN ('ACTIVO','INACTIVO'))
ENABLE;

--
ALTER TABLE CONSTANTES 
ADD (ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL);

ALTER TABLE CONSTANTES
ADD CONSTRAINT CONSTANTES_CHK1 CHECK 
(ESTADO IN ('ACTIVO', 'INACTIVO'))
ENABLE;

--
ALTER TABLE AREA_CIENCIA_TECNOLOGIA 
ADD (ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL);

ALTER TABLE AREA_CIENCIA_TECNOLOGIA
ADD CONSTRAINT AREA_CIENCIA_TECNOLOGIA_CHK1 CHECK 
(ESTADO IN ('ACTIVO', 'INACTIVO')
)
ENABLE;

--
ALTER TABLE LINEA 
ADD (ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL);

ALTER TABLE LINEA
ADD CONSTRAINT LINEA_CHK1 CHECK 
(ESTADO IN ('ACTIVO', 'INACTIVO')
)
ENABLE;

--
ALTER TABLE TEMA 
ADD (ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL);

ALTER TABLE TEMA
ADD CONSTRAINT TEMA_CHK1 CHECK 
(ESTADO IN ('ACTIVO', 'INACTIVO'))
ENABLE;



insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1008, 'TIPO_PARAMETROS_SISTEMA', 'Grupo de investigación', 'Grupo de investigación');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1009, 'TIPO_PARAMETROS_SISTEMA', 'Instituciones', 'Instituciones');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1010, 'TIPO_PARAMETROS_SISTEMA', 'Áreas de investigación', 'Áreas de investigación');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1011, 'TIPO_PARAMETROS_SISTEMA', 'Líneas de investigación', 'Líneas de investigación');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1012, 'TIPO_PARAMETROS_SISTEMA', 'Tipo de investigador', 'Tipo de investigador');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1013, 'TIPO_PARAMETROS_SISTEMA', 'Ítems para el planteamiento del proyecto', 'Ítems para el planteamiento del proyecto');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1014, 'TIPO_PARAMETROS_SISTEMA', 'Ítems para resultados obtenidos en informe de final implementación', 'Ítems para resultados obtenidos en informe de final implementación');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1015, 'TIPO_PARAMETROS_SISTEMA', 'Ítems en información a tener en cuenta en la implementación', 'Ítems en información a tener en cuenta en la implementación');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1016, 'TIPO_PARAMETROS_SISTEMA', 'Ítems en informe de avance de implementación', 'Ítems en informe de avance de implementación');

insert into constantes(ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (1017, 'TIPO_PARAMETROS_SISTEMA', 'Ítems en información a tener en cuenta informe de avance implementación', 'Ítems en información a tener en cuenta informe de avance implementación');

INSERT INTO OPCION_MENU (ID_OPCION_MENU, NOMBRE, TIPO_ACCESO, ACCION, ID_OPCION_MENU2, TITULO) VALUES (43, 'Parámetros', 'PRIVADO', 'BEAN:#{cuAd02AdministrarParametrosSistemaFaces.initReturnCU}', 8, 'Permite al usuario gestionar los parámetros del sistema ');

INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES (66, 2, 43);

insert into USUARIO_ROL (ID_USUARIO_ROL, IDENTIFICADOR_USUARIO, ID_ROL, FECHA_INICIO, ACTIVO)
VALUES (SEC_USUARIO_ROL.NEXTVAL, 'SIAT_123-ADMIN', 2, SYSDATE, 'S');

insert into constantes select * from DINAE1_2ITERACION_FINAL_TEST.constantes;
insert into key_properties select * from DINAE1_2ITERACION_FINAL_TEST.key_properties;
insert into vista_funcionario select * from DINAE1_2ITERACION_FINAL_TEST.vista_funcionario;
insert into correo_parametriza select * from DINAE1_2ITERACION_FINAL_TEST.correo_parametriza;
insert into area_ciencia_tecnologia select * from DINAE1_2ITERACION_FINAL_TEST.area_ciencia_tecnologia;
insert into criterio_evaluacion select * from DINAE1_2ITERACION_FINAL_TEST.criterio_evaluacion;
insert into criterio_evaluacion select * from DINAE1_2ITERACION_FINAL_TEST.criterio_evaluacion;
insert into grados_valores select * from DINAE1_2ITERACION_FINAL_TEST.grados_valores;
insert into GRUPO_INVESTIGACION select * from DINAE1_2ITERACION_FINAL_TEST.GRUPO_INVESTIGACION;
insert into LINEA select * from DINAE1_2ITERACION_FINAL_TEST.LINEA;
insert into OPCION_MENU select * from DINAE1_2ITERACION_FINAL_TEST.OPCION_MENU;
insert into PROGRAMAS select * from DINAE1_2ITERACION_FINAL_TEST.PROGRAMAS;
insert into ROL select * from DINAE1_2ITERACION_FINAL_TEST.ROL;
insert into ROL_OPCION_MENU select * from DINAE1_2ITERACION_FINAL_TEST.ROL_OPCION_MENU;
insert into TEMA select * from DINAE1_2ITERACION_FINAL_TEST.TEMA;
insert into TIPO_UNIDAD select * from DINAE1_2ITERACION_FINAL_TEST.TIPO_UNIDAD;
insert into UNIDAD_POLICIAL select * from DINAE1_2ITERACION_FINAL_TEST.UNIDAD_POLICIAL;
insert into USUARIO_ROL select * from DINAE1_2ITERACION_FINAL_TEST.USUARIO_ROL;
insert into USUARIO_UNIDAD_POLICIAL select * from DINAE1_2ITERACION_FINAL_TEST.USUARIO_UNIDAD_POLICIAL;

ALTER SEQUENCE SEC_TEMA INCREMENT BY 100;
SELECT SEC_TEMA.NEXTVAL FROM DUAL;
ALTER SEQUENCE SEC_TEMA INCREMENT BY 1;

ALTER TABLE PROPUESTA_NECESIDAD ADD IDENTIFICADOR_USUARIO_CREACION VARCHAR2(100);
ALTER TABLE PLAN_TRABAJO_IMPLEMENTACION MODIFY OBJETIVOS_ESPECIFICOS VARCHAR2(1200);
ALTER TABLE PLAN_TRABAJO_IMPLEMENTACION MODIFY OBJETIVO_GRAL_IMPLEMENTACION VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY MISION_SEMILLERO VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY VISION_SEMILLERO VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY OBJETIVO_GENERAL VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY OBJETIVO_ESPECIFICO VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY METODOLOGIA_TRABAJO VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY PRODUCTO_O_RESULTADO VARCHAR2(600);
ALTER TABLE SEMILLERO_INVESTIGACION MODIFY NOMBRE_RED_NODO_PERTENECE VARCHAR2(600);
ALTER TABLE RECURSO_HUMANO_SEMILLERO MODIFY COMPANIA VARCHAR2(100);
ALTER TABLE COMPROMISO_IMPLEMENTACION MODIFY COMENTARIO_TEMPORAL VARCHAR2(700);
ALTER TABLE compromiso_proyecto MODIFY COMENTARIO_TEMPORAL VARCHAR2(700);
ALTER TABLE COMENTARIO_COMPROMISO_PROYECTO MODIFY COMENTARIO VARCHAR2(700);
ALTER TABLE INFORME_AVANCE_IMPLEMENTACION MODIFY NRO_ACTA_APROBACION_COMITE VARCHAR2(100);
ALTER TABLE PERIODO MODIFY NOMBRE_CONVOCATORIA VARCHAR2(400);

--------------------------------------------------------------------------------------
---- PRESUPUESTO IMPLEMENATCION ------------------------------------------------------

ALTER TABLE FUENTE_PROYECTO
MODIFY ID_PROYECTO NULL;

ALTER TABLE evento_proyecto
MODIFY ID_PROYECTO NULL;


ALTER TABLE INVESTIGADORES_PROYECTO
ADD VALOR_HORA_INVESTIGADOR_IMPL NUMBER(12,2);

alter table EJECUCION_EQUIPOS_PROYECTO
modify ID_INFORME_AVANCE null;

alter table EJECUCION_EQUIPOS_PROYECTO
ADD ID_INFORME_IMPLEMENTACION NUMBER;

alter table EJECUCION_EQUIPOS_PROYECTO
add constraint EJECU_EQUIPOS_IMPL_FK foreign key (ID_INFORME_IMPLEMENTACION) references INFORME_AVANCE_IMPLEMENTACION(ID_INFORME_AVANCE_IMPL);

-------------------------------------------------
alter table EJECUCION_EVENTOS_PROYECTO
modify ID_INFORME_AVANCE null;

alter table EJECUCION_EVENTOS_PROYECTO
ADD ID_INFORME_IMPLEMENTACION NUMBER;

alter table EJECUCION_EVENTOS_PROYECTO
add constraint EJECU_EVENTOS_IMPL_FK foreign key (ID_INFORME_IMPLEMENTACION) references INFORME_AVANCE_IMPLEMENTACION(ID_INFORME_AVANCE_IMPL);

-------------------------------------------------

alter table EJECUCION_OTROS_GASTOS_PROY
modify ID_INFORME_AVANCE null;

alter table EJECUCION_OTROS_GASTOS_PROY
ADD ID_INFORME_IMPLEMENTACION NUMBER;

alter table EJECUCION_OTROS_GASTOS_PROY
add constraint EJECU_OTROS_GASTOS_IMPL_FK foreign key (ID_INFORME_IMPLEMENTACION) references INFORME_AVANCE_IMPLEMENTACION(ID_INFORME_AVANCE_IMPL);

-------------------------------------------------

alter table EJECUCION_VIAJES_PROYECTO
modify ID_INFORME_AVANCE null;

alter table EJECUCION_VIAJES_PROYECTO
ADD ID_INFORME_IMPLEMENTACION NUMBER;

alter table EJECUCION_VIAJES_PROYECTO
add constraint EJECU_VIAJES_IMPL_FK foreign key (ID_INFORME_IMPLEMENTACION) references INFORME_AVANCE_IMPLEMENTACION(ID_INFORME_AVANCE_IMPL);

-------------------------------------------------

ALTER TABLE PERIODO MODIFY NOMBRE_CONVOCATORIA VARCHAR2(400);
ALTER TABLE PROYECTO MODIFY NRO_ACTA_APROBACION_COMITE VARCHAR2(50);
ALTER TABLE ACTIVIDADES_REALIZADAS_PROY MODIFY DESCRIPCION_ACTIVIDAD VARCHAR2(600);
ALTER TABLE RESULTADOS_ALCANZADOS_PROY MODIFY RESULTADO_ALCANZADO VARCHAR2(600);
ALTER TABLE SUGERENCIAS_PROY MODIFY SUGERENCIA VARCHAR2(600);
ALTER TABLE EVIDENCIA_PROYECTO MODIFY DESCRIPCION VARCHAR2(600);
ALTER TABLE INFORME_AVANCE MODIFY TIPO_CONTENIDO_ARCHIVO VARCHAR2(300);
ALTER TABLE RESULTADOS_INVESTIGACION MODIFY DESCRIPCION VARCHAR2(600);
ALTER TABLE EVENTO_INVESTIGACION MODIFY DESCRIPCION VARCHAR2(700);

ALTER TABLE INVESTI_DESARROL_INVESTTIGADOR MODIFY TITULO_INVESTIGACION VARCHAR2(300);
ALTER TABLE INVESTI_DESARROL_INVESTTIGADOR MODIFY RESUMEN VARCHAR2(700);
ALTER TABLE INVESTI_DESARROL_INVESTTIGADOR MODIFY TITULO_INVESTIGACION VARCHAR2(700);

ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY TITULO_PUBLICACION VARCHAR2(700);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY RESUMEN_PUBLICACION VARCHAR2(700);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY CODIGO_ISSN VARCHAR2(50);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY VOLUMEN_REVISTA VARCHAR2(50);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY FASCICULO_REVISTA VARCHAR2(50);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY SERIE_REVISTA VARCHAR2(50);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY CODIGO_ISBN VARCHAR2(50);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY NOMBRE_LIBRO VARCHAR2(200);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY EDITORIAL_LIBRO VARCHAR2(200);
ALTER TABLE PUBLICACION_INVESTIGADOR MODIFY NOMBRE_REVISTA VARCHAR2(200);


ALTER TABLE PROYECTO_VERSION MODIFY NRO_ACTA_APROBACION_COMITE VARCHAR(50);

------ PRESUPUESTO IMPLEMENTACION -----------

    DROP TABLE RESUMEN_PRESUPUESTO_IMPL;

    CREATE TABLE RESUMEN_PRESUPUESTO_IMPL 
       (	ID_RESUMEN_PRESUPUESTO_IMPL NUMBER PRIMARY KEY, 
            ID_IMPLEMENTACION_PROY NUMBER NOT NULL, 
      ID_PLAN_TRABAJO NUMBER NOT NULL, 
            NOMBRE_RUBRO VARCHAR2(30) NOT NULL , 
            POLICIA_NACIONAL_ESPECIE NUMBER(20,2) DEFAULT 0, 
            POLICIA_NACIONAL_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            VICIN_ESPECIE NUMBER(20,2) DEFAULT 0, 
            VICIN_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            UNIDAD_ESPECIE NUMBER(20,2) DEFAULT 0, 
            UNIDAD_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            FUENTE1_ESPECIE NUMBER(20,2) DEFAULT 0, 
            FUENTE1_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            FUENTE2_ESPECIE NUMBER(20,2) DEFAULT 0, 
            FUENTE2_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            FUENTE3_ESPECIE NUMBER(20,2) DEFAULT 0, 
            FUENTE3_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            FUENTE4_ESPECIE NUMBER(20,2) DEFAULT 0, 
            FUENTE4_EFECTIVO NUMBER(20,2) DEFAULT 0, 
            ORDEN NUMBER, 
            ES_FUENTE1_INTERNA VARCHAR2(1), 
            ES_FUENTE2_INTERNA VARCHAR2(1), 
            ES_FUENTE3_INTERNA VARCHAR2(1), 
            ES_FUENTE4_INTERNA VARCHAR2(1), 
            ESTADO VARCHAR2(100) DEFAULT 'TEMPORAL'); 

       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.ID_RESUMEN_PRESUPUESTO_IMPL IS 'Identificador único';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.ID_IMPLEMENTACION_PROY IS 'Identificador de la implementación del proyecto';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.ID_PLAN_TRABAJO IS 'Identificador del plan de trabajo de la implementación';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.NOMBRE_RUBRO IS 'Nombre del rubro';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.POLICIA_NACIONAL_ESPECIE IS 'Valor policía en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.POLICIA_NACIONAL_EFECTIVO IS 'Valor policía en efectivo';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.VICIN_ESPECIE IS 'Valor VICIN en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.VICIN_EFECTIVO IS 'Valor VICIN en efectivo';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.UNIDAD_ESPECIE IS 'Valor de la unidad en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.UNIDAD_EFECTIVO IS 'Valor de la unidad en efectivo';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE1_ESPECIE IS 'Valor de la fuente 1 en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE1_EFECTIVO IS 'Valor de la fuente en efectivo';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE2_ESPECIE IS 'Valor de la fuente 2  en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE2_EFECTIVO IS 'Valor de la fuente 2 en efectivo';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE3_ESPECIE IS 'Valor de la fuente 3 en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE3_EFECTIVO IS 'Valor de la fuente3 en efectivo';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE4_ESPECIE IS 'Valor de la fuente 4 en especie';
       COMMENT ON COLUMN RESUMEN_PRESUPUESTO_IMPL.FUENTE4_EFECTIVO IS 'Valor de la fuente 4 en efectivo';


      CREATE TABLE RESUMEN_PRES_EJECUTA_IMPL
       (	ID_RESUMEN_PRES_EJECUTA_IMPL NUMBER PRIMARY KEY NOT NULL , 
            ID_IMPLEMENTACION_PROYECTO NUMBER NOT NULL , 
            ID_INFORME_AVANCE_IMPL NUMBER, 
            NOMBRE_RUBRO VARCHAR2(30) NOT NULL , 
            POLICIA_NAL_PPTO NUMBER(20,2) DEFAULT 0, 
            POLICIA_NAL_EJECUTA NUMBER(20,2) DEFAULT 0, 
            VICIN_PPTO NUMBER(20,2) DEFAULT 0, 
            VICIN_EJECUTA NUMBER(20,2) DEFAULT 0, 
            UNIDAD_PPTO NUMBER(20,2) DEFAULT 0, 
            UNIDAD_EJECUTA NUMBER(20,2) DEFAULT 0, 
            FUENTE1_PPTO NUMBER(20,2) DEFAULT 0, 
            FUENTE1_EJECUTA NUMBER(20,2) DEFAULT 0, 
            FUENTE2_PPTO NUMBER(20,2) DEFAULT 0, 
            FUENTE2_EJECUTA NUMBER(20,2) DEFAULT 0, 
            FUENTE3_PPTO NUMBER(20,2) DEFAULT 0, 
            FUENTE3_EJECUTA NUMBER(20,2) DEFAULT 0, 
            FUENTE4_PPTO NUMBER(20,2) DEFAULT 0, 
            FUENTE4_EJECUTA NUMBER(20,2) DEFAULT 0, 
            ORDEN NUMBER, 
            TIPO VARCHAR2(1) DEFAULT 'I' NOT NULL );


ALTER TABLE DETALLE_EVALUACION MODIFY SUGERENCIA_RECOMENDACION VARCHAR2(700);

--0003126
UPDATE KEY_PROPERTIES SET VALOR = 'No se encontraron compromisos para el periodo seleccionado.' WHERE CLAVE = 'cu_pr_24_lbl_no_tipo_compromiso_convocatoria_lista_vacia';
--0003127
UPDATE KEY_PROPERTIES SET VALOR = 'No se encontraron compromisos para la convocatoria seleccionada.' WHERE CLAVE = 'cu_pr_24_lbl_no_tipo_compromiso_convocatoria_lista_vacia';
--0003131
--0003132
UPDATE KEY_PROPERTIES SET VALOR = 'El número de identificación ingresado no existe en el sistema' WHERE CLAVE = 'cu_pr_21_info_persona_no_encontrada';
--0003133
--0003134
--0003135
--0003136
--0003137
--0003138
--0003002
--0002807
UPDATE KEY_PROPERTIES SET VALOR = 'Fecha incio' WHERE VALOR = 'Fecha de inicio';
UPDATE KEY_PROPERTIES SET VALOR = 'Fecha fin' WHERE VALOR = 'Fecha de fin';
--0003009
--0003010
--0003011
--0003140
--0003142
--0003143
UPDATE KEY_PROPERTIES SET VALOR = 'La publicación ha sido almacenada.' WHERE CLAVE = 'cu_iv_01_info_guardar_investigacion_exitosa';
--0003073
--0003145
--0003146
--0003147
--0003111
--0003147
--0003112
--0003115
--0003116
--0003148
--0003160
--0003203
--0002686
--0003110
--0003109
--0003107
--0003108
--0003106
--0003105
--0003117
UPDATE KEY_PROPERTIES SET VALOR = 'No existen compromisos con resultado No aceptado, para enviar al Grupo de investigación' WHERE CLAVE = 'cu_pr_25_lbl_mensaje_error_noexisten_propuesta_envia_grupo_inves';
--0003101
--0003091
--0002577
--0002554
--0002622
--0002623
--0002628
--0002584
--0002650
--0002652
--0002680
--0002683
--0002685
--0002702
--0002702
--0002709
--0002711
--0002712
--0002695
--0002758
--0002759
--0002764
--0002765
--0002784


ALTER TABLE EVENTO_PROYECTO MODIFY TITULO_EVENTO VARCHAR(600);
ALTER TABLE EVENTO_PROYECTO MODIFY OBJETIVO_EVENTO VARCHAR(600);

create or replace PROCEDURE CREA_V_PRESU_PRO_CUMPLIDO_IMPL (P_ID_COMPROMISO_IMPL IN NUMBER, P_ID_IMPLEMENTACION_PROY  IN NUMBER) AS  

  P_ID_PLAN_TRABAJO plan_trabajo_implementacion.ID_PLAN_TRABAJO%TYPE;
  P_TIPO_COMPRO_IMPL compromiso_implementacion.ID_TIPO_COMPROMISO%TYPE;
  P_ID_INFORME_AVANCE_IMPL compromiso_implementacion.ID_TIPO_COMPROMISO%TYPE;
  P_COMPROMISO_ACUMULA RESUMEN_PRES_EJECUT_IMPL_COPIA.COMPROMISO_ACUMULA%TYPE;
  
BEGIN    
        
    select ID_TIPO_COMPROMISO  into P_TIPO_COMPRO_IMPL FROM compromiso_implementacion
        WHERE id_compromiso_implementacion = P_ID_COMPROMISO_IMPL;
    
    --226	TIPO_COMPROMISO_IMPLEMENTACION	Plan de Trabajo
    --227	TIPO_COMPROMISO_IMPLEMENTACION	Informe de avance de implementación
    --228	TIPO_COMPROMISO_IMPLEMENTACION	Informe final de implementación    
    IF P_TIPO_COMPRO_IMPL = 226 THEN
    
        select id_plan_trabajo into P_ID_PLAN_TRABAJO 
          from plan_trabajo_implementacion 
            WHERE id_compromiso_implementacion = P_ID_COMPROMISO_IMPL AND id_implementacion_proy = P_ID_IMPLEMENTACION_PROY;
            
        PKG_CALCULO_PRESUPUESTO_IMPL.PRC_CREAR_ACTUALIZA_PRES( P_ID_PLAN_TRABAJO, P_ID_IMPLEMENTACION_PROY );
        DELETE FROM RESUMEN_PRESUPUESTO_IMPL WHERE ID_IMPLEMENTACION_PROY = P_ID_IMPLEMENTACION_PROY AND ID_PLAN_TRABAJO = P_ID_PLAN_TRABAJO AND ESTADO = 'COMPROMISO_CUMPLIDO_PLAN_TRABAJO';
        UPDATE RESUMEN_PRESUPUESTO_IMPL set ESTADO = 'COMPROMISO_CUMPLIDO_PLAN_TRABAJO' WHERE ID_IMPLEMENTACION_PROY = P_ID_IMPLEMENTACION_PROY AND ID_PLAN_TRABAJO = P_ID_PLAN_TRABAJO;
        
    ELSE
        
        select ID_INFORME_AVANCE_IMPL into P_ID_INFORME_AVANCE_IMPL 
          from informe_avance_implementacion 
            WHERE id_compromiso_implementacion = P_ID_COMPROMISO_IMPL AND id_implementacion_proy = P_ID_IMPLEMENTACION_PROY;
        
        PKG_CALCULO_PRESUPUESTO_IMPL.PRC_CALCULAR_PRES_EJECUTA( P_ID_IMPLEMENTACION_PROY, P_ID_INFORME_AVANCE_IMPL );
        
          IF P_TIPO_COMPRO_IMPL = 227 THEN
                     
                DELETE FROM RESUMEN_PRES_EJECUT_IMPL_COPIA WHERE ID_IMPLEMENTACION_PROYECTO = P_ID_IMPLEMENTACION_PROY AND ID_INFORME_AVANCE_IMPL IS NOT NULL;   
                  insert into RESUMEN_PRES_EJECUT_IMPL_COPIA ( 
                  ID_RESUMEN_PRES_EJECUTA_IMPL,
                  ID_IMPLEMENTACION_PROYECTO,
                  ID_INFORME_AVANCE_IMPL,
                  NOMBRE_RUBRO,
                  POLICIA_NAL_PPTO,
                  POLICIA_NAL_EJECUTA,
                  VICIN_PPTO,
                  VICIN_EJECUTA,
                  UNIDAD_PPTO,
                  UNIDAD_EJECUTA,
                  FUENTE1_PPTO,
                  FUENTE1_EJECUTA,
                  FUENTE2_PPTO,
                  FUENTE2_EJECUTA,
                  FUENTE3_PPTO,
                  FUENTE3_EJECUTA,
                  FUENTE4_PPTO,
                  FUENTE4_EJECUTA,
                  ORDEN,
                  COMPROMISO_ACUMULA) 
                  select 
                  rpe.ID_RESUMEN_PRES_EJECUTA_IMPL,
                  rpe.ID_IMPLEMENTACION_PROYECTO,
                  rpe.ID_INFORME_AVANCE_IMPL,
                  rpe.NOMBRE_RUBRO,
                  rpe.POLICIA_NAL_PPTO,
                  rpe.POLICIA_NAL_EJECUTA,
                  rpe.VICIN_PPTO,
                  rpe.VICIN_EJECUTA,
                  rpe.UNIDAD_PPTO,
                  rpe.UNIDAD_EJECUTA,
                  rpe.FUENTE1_PPTO,
                  rpe.FUENTE1_EJECUTA,
                  rpe.FUENTE2_PPTO,
                  rpe.FUENTE2_EJECUTA,
                  rpe.FUENTE3_PPTO,
                  rpe.FUENTE3_EJECUTA,
                  rpe.FUENTE4_PPTO,
                  rpe.FUENTE4_EJECUTA,
                  rpe.ORDEN,
                  'ACUMULA_COMPROMISO_SOLO_AVANCE' AS COMPROMISO_ACUMULA
            from RESUMEN_PRES_EJECUTA_IMPL rpe WHERE rpe.ID_IMPLEMENTACION_PROYECTO = P_ID_IMPLEMENTACION_PROY AND rpe.ID_INFORME_AVANCE_IMPL IS NOT NULL;
                     
          ELSIF P_TIPO_COMPRO_IMPL = 228 THEN
                    
                  DELETE FROM RESUMEN_PRES_EJECUT_IMPL_COPIA WHERE ID_IMPLEMENTACION_PROYECTO = P_ID_IMPLEMENTACION_PROY AND ID_INFORME_AVANCE_IMPL IS NULL;  
                   insert into RESUMEN_PRES_EJECUT_IMPL_COPIA ( 
                  ID_RESUMEN_PRES_EJECUTA_IMPL,
                  ID_IMPLEMENTACION_PROYECTO,
                  ID_INFORME_AVANCE_IMPL,
                  NOMBRE_RUBRO,
                  POLICIA_NAL_PPTO,
                  POLICIA_NAL_EJECUTA,
                  VICIN_PPTO,
                  VICIN_EJECUTA,
                  UNIDAD_PPTO,
                  UNIDAD_EJECUTA,
                  FUENTE1_PPTO,
                  FUENTE1_EJECUTA,
                  FUENTE2_PPTO,
                  FUENTE2_EJECUTA,
                  FUENTE3_PPTO,
                  FUENTE3_EJECUTA,
                  FUENTE4_PPTO,
                  FUENTE4_EJECUTA,
                  ORDEN,
                  COMPROMISO_ACUMULA) 
                  select 
                  rpe.ID_RESUMEN_PRES_EJECUTA_IMPL,
                  rpe.ID_IMPLEMENTACION_PROYECTO,
                  rpe.ID_INFORME_AVANCE_IMPL,
                  rpe.NOMBRE_RUBRO,
                  rpe.POLICIA_NAL_PPTO,
                  rpe.POLICIA_NAL_EJECUTA,
                  rpe.VICIN_PPTO,
                  rpe.VICIN_EJECUTA,
                  rpe.UNIDAD_PPTO,
                  rpe.UNIDAD_EJECUTA,
                  rpe.FUENTE1_PPTO,
                  rpe.FUENTE1_EJECUTA,
                  rpe.FUENTE2_PPTO,
                  rpe.FUENTE2_EJECUTA,
                  rpe.FUENTE3_PPTO,
                  rpe.FUENTE3_EJECUTA,
                  rpe.FUENTE4_PPTO,
                  rpe.FUENTE4_EJECUTA,
                  rpe.ORDEN,
                  'ACUMULA_COMPROMISO_AVANCE_Y_FINAL' AS COMPROMISO_ACUMULA
            from RESUMEN_PRES_EJECUTA_IMPL rpe WHERE rpe.ID_IMPLEMENTACION_PROYECTO = P_ID_IMPLEMENTACION_PROY AND rpe.ID_INFORME_AVANCE_IMPL IS NULL;
            
          END IF;
                              
    END IF;    
    
END CREA_V_PRESU_PRO_CUMPLIDO_IMPL;


CREATE TABLE RESUMEN_PRES_EJECUT_IMPL_COPIA
  (
    ID_RESUMEN_PRES_EJECUTA_IMPL NUMBER NOT NULL,
    ID_IMPLEMENTACION_PROYECTO   NUMBER NOT NULL,
    ID_INFORME_AVANCE_IMPL       NUMBER,
    NOMBRE_RUBRO                 VARCHAR2(30) NOT NULL,
    POLICIA_NAL_PPTO             NUMBER(20,2) DEFAULT 0,
    POLICIA_NAL_EJECUTA          NUMBER(20,2) DEFAULT 0,
    VICIN_PPTO                   NUMBER(20,2) DEFAULT 0,
    VICIN_EJECUTA                NUMBER(20,2) DEFAULT 0,
    UNIDAD_PPTO                  NUMBER(20,2) DEFAULT 0,
    UNIDAD_EJECUTA               NUMBER(20,2) DEFAULT 0,
    FUENTE1_PPTO                 NUMBER(20,2) DEFAULT 0,
    FUENTE1_EJECUTA              NUMBER(20,2) DEFAULT 0,
    FUENTE2_PPTO                 NUMBER(20,2) DEFAULT 0,
    FUENTE2_EJECUTA              NUMBER(20,2) DEFAULT 0,
    FUENTE3_PPTO                 NUMBER(20,2) DEFAULT 0,
    FUENTE3_EJECUTA              NUMBER(20,2) DEFAULT 0,
    FUENTE4_PPTO                 NUMBER(20,2) DEFAULT 0,
    FUENTE4_EJECUTA              NUMBER(20,2) DEFAULT 0,
    ORDEN                        NUMBER,
    TIPO                         VARCHAR2(1) DEFAULT 'I' NOT NULL,
    COMPROMISO_ACUMULA           VARCHAR2(100) NOT NULL
  );