 CREATE SEQUENCE SEC_INFORME_AVANCE
  INCREMENT by 1
  MINVALUE 1
;

ALTER TABLE INFORME_AVANCE ADD ID_TIPO_INFORME NUMBER;
ALTER TABLE INFORME_AVANCE ADD CONSTRAINT TIPO_INFORME_AV_CONSTANTES_FK FOREIGN KEY (ID_TIPO_INFORME) REFERENCES CONSTANTES (ID_CONSTANTES);

DROP TABLE VIAJES_PROYECTO CASCADE CONSTRAINTS ;	
CREATE TABLE VIAJES_PROYECTO
  (
    ID_VIAJE_PROYECTO        NUMBER NOT NULL ,
    ID_INVESTIGADOR_PROYECTO NUMBER NOT NULL ,    
    EVENTO                   VARCHAR2(512) NOT NULL ,
    CODIGO_CIUDAD_ORIGEN     VARCHAR2(6) NOT NULL ,
    NOMBRE_CIUDAD_ORIGEN     VARCHAR2(100) NOT NULL ,
    CODIGO_CIUDAD_DESTINO    VARCHAR2(6) NOT NULL ,
    NOMBRE_CIUDAD_DESTINO    VARCHAR2(100) NOT NULL ,
    COSTOS_PASAJES           NUMBER(11,2) NOT NULL ,
    COSTOS_VIATICOS          NUMBER(11,2) NOT NULL ,
    ID_FUENTE_PROYECTO       NUMBER,
    CONSTRAINT VIAJES_PROYECTO_PK PRIMARY KEY (ID_VIAJE_PROYECTO), 
    CONSTRAINT VIAJE_PROYE_INVESTI_PROYEC_FK FOREIGN KEY (ID_INVESTIGADOR_PROYECTO) REFERENCES INVESTIGADORES_PROYECTO (ID_INVESTIGADOR_PROYECTO),
	CONSTRAINT FUENTE_PROY_INVESTI_PROYEC_FK FOREIGN KEY (ID_FUENTE_PROYECTO) REFERENCES FUENTE_PROYECTO (ID_FUENTE_PROYECTO)	
  );
  
 drop SEQUENCE SEC_VIAJES_PROYECTO;
 CREATE SEQUENCE SEC_VIAJES_PROYECTO
  INCREMENT by 1
  MINVALUE 1
;

DROP TABLE CIUDAD CASCADE CONSTRAINTS ;	

drop table RESENIA_INVESTIGACION cascade constraints;
CREATE TABLE RESENIA_INVESTIGACION
  (
    ID_RESENIA_INVESTIGACION NUMBER NOT NULL ,
    RESUMEN_PALABRAS         VARCHAR2(4000 ) NOT NULL ,
    PALABRAS_CLAVE           VARCHAR2(4000 ),
    ABSTRACT                 VARCHAR2(4000 ),
    KEYWORDS                 VARCHAR2(4000 ),
    CONCLUSION               VARCHAR2(4000 ),
    RECOMENDACIONES          VARCHAR2(4000 ),
    ID_PROYECTO              NUMBER NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL ,
    ID_USUARIO_ROL    NUMBER NOT NULL ,
    ID_INFORME_AVANCE NUMBER NOT NULL ,
    CONSTRAINT RESENIA_INVESTIGACION_PK PRIMARY KEY (ID_RESENIA_INVESTIGACION) ,
    CONSTRAINT RESE_INVEST_PROY_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO) ,
    CONSTRAINT INFORME_AVANCE_FK FOREIGN KEY (ID_INFORME_AVANCE) REFERENCES INFORME_AVANCE (ID_INFORME_AVANCE) 
  );

drop table RESULTADOS_INVESTIGACION cascade constraints;
  CREATE TABLE RESULTADOS_INVESTIGACION
  (
    ID_RESULTADO_INVESTIGACION NUMBER NOT NULL ,
    ID_TIPO_PRODUCTO           NUMBER NOT NULL ,
    DESCRIPCION                VARCHAR2(512),
    FECHA_REGISTRO TIMESTAMP (6) NOT NULL ,
    ID_USUARIO_ROL    NUMBER NOT NULL ,
    ID_PROYECTO       NUMBER NOT NULL ,
    ID_INFORME_AVANCE NUMBER,
    CONSTRAINT RESULTADOS_INVESTIGACION_PK PRIMARY KEY (ID_RESULTADO_INVESTIGACION),
    CONSTRAINT RESUL_AVAN_PROY_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO) ,
    CONSTRAINT RESUL_USUARIOROL_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) ,
    CONSTRAINT RESUL_CONSTANTES_FK FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT INFORME_AVANCE_RES_FK FOREIGN KEY (ID_INFORME_AVANCE) REFERENCES INFORME_AVANCE (ID_INFORME_AVANCE) 
  );

drop table EQUIPOS_INVESTIGACION cascade constraints;
  CREATE TABLE EQUIPOS_INVESTIGACION
  (
    ID_EQUIPO_INVESTIGACION NUMBER NOT NULL ,
    VALOR                   NUMBER(15,2) NOT NULL ,
    ESPECIFICACIONES        VARCHAR2(512 ) NOT NULL ,
    ID_FUENTE_PROYECTO      NUMBER NOT NULL ,
    ID_ORIGEN               NUMBER NOT NULL ,
    NOMBRE_EQUIPO           VARCHAR2(250 ),
    CONSTRAINT EQUIPOS_INVESTIGACION_PK PRIMARY KEY (ID_EQUIPO_INVESTIGACION),
    CONSTRAINT EQUIPOS_FUENTEPROYECTO_FK FOREIGN KEY (ID_FUENTE_PROYECTO) REFERENCES FUENTE_PROYECTO (ID_FUENTE_PROYECTO), 
	CONSTRAINT EQUIPOS_CONSTANTES_FK FOREIGN KEY (ID_ORIGEN) REFERENCES CONSTANTES (ID_CONSTANTES) 
  );

--06 de Nov de 2013
CREATE SEQUENCE  SEC_RESULTADOS_INVESTIGACION  
 INCREMENT BY 1 
 START WITH 1
;

CREATE SEQUENCE  SEC_RESENIA_INVESTIGACION  
 INCREMENT BY 1 
 START WITH 1
;

drop table HORAS_INVESTIGADOR cascade constraints;
CREATE TABLE HORAS_INVESTIGADOR
  (
    ID_HORAS_INVESTIGADOR NUMBER NOT NULL ,
    HORAS_INVESTIGA_TRAB_PERI NUMBER NOT NULL ,
    ID_PROYECTO NUMBER NOT NULL,
    ID_INVESTIGADOR_PROYECTO NUMBER NOT NULL,
    ID_COMPROMISO_PROYECTO NUMBER NOT NULL,    
    CONSTRAINT HORAS_INVESTIGADOR_PK PRIMARY KEY (ID_HORAS_INVESTIGADOR),
    CONSTRAINT ID_PROYECTO_HOR_PROYECTO_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO), 
    CONSTRAINT ID_INVESTIGA_INVESTI_PROYEC_FK FOREIGN KEY (ID_INVESTIGADOR_PROYECTO) REFERENCES INVESTIGADORES_PROYECTO (ID_INVESTIGADOR_PROYECTO), 
    CONSTRAINT ID_COMPRO_PROY_COMPROPROY_FK FOREIGN KEY (ID_COMPROMISO_PROYECTO) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO) 
  );

CREATE SEQUENCE  SEC_HORAS_INVESTIGADOR
 INCREMENT BY 1 
 START WITH 1
;

CREATE TABLE SUGERENCIAS_PROY
  (
    ID_SUGERENCIAS_PROY NUMBER NOT NULL ,
    SUGERENCIA       VARCHAR2(512) NOT NULL ,
    ID_COMPROMISO_PROYECTO      NUMBER NOT NULL ,
    ID_PROYECTO    NUMBER NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL ,
    ID_USUARIO_ROL NUMBER NOT NULL ,
    MAQUINA        VARCHAR2(100),
    CONSTRAINT SUGERENCIAS_PROYECTO_PK PRIMARY KEY (ID_SUGERENCIAS_PROY),
	CONSTRAINT PROYECTO_SUGE_PRO_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
	CONSTRAINT USUARIO_SUGE_PRO_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL),
	CONSTRAINT COMPROMISO_SUGE_PRO_FK FOREIGN KEY (ID_COMPROMISO_PROYECTO) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO)
  );

CREATE SEQUENCE SEC_SUGERENCIAS_PRO
  START WITH 1
  INCREMENT by 1
  MINVALUE 1
;

ALTER TABLE INDICADORES_PROYECTO ADD CASO_USO VARCHAR2(50);
ALTER TABLE INDICADORES_PROYECTO ADD VALOR_NUMERADOR NUMBER;
ALTER TABLE INDICADORES_PROYECTO ADD VALOR_DENOMINADOR NUMBER;

ALTER TABLE INFORME_AVANCE ADD ID_COMPROMISO_PROYECTO NUMBER;
ALTER TABLE INFORME_AVANCE ADD CONSTRAINT COMPROMISO_INFORE_AVAN_FK FOREIGN KEY (ID_COMPROMISO_PROYECTO) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO);

CREATE TABLE INVESTIGADOR 
(
  ID_INVESTIGADOR NUMBER NOT NULL, 
  NUMERO_IDENTIFICACION VARCHAR2(20) NOT NULL, 
  CODIGO_CIUDAD_EXPEDICION VARCHAR2(6), 
  NOMBRE_CIUDAD_EXPEDICION VARCHAR2(100), 
  NOMBRES VARCHAR2(100) NOT NULL, 
  APELLIDOS VARCHAR2(100) NOT NULL, 
  CORREO_ELECTRONICO VARCHAR2(100) NOT NULL, 
  TELEFONO VARCHAR2(20) NOT NULL, 
  DIRECCION VARCHAR2(100) NOT NULL, 
  CODIGO_DEPTO_RESIDENCIA VARCHAR2(6) NOT NULL, 
  NOMBRE_DEPTO_RESIDENCIA VARCHAR2(100) NOT NULL, 
  CODIGO_CIUDAD_RESIDENCIA VARCHAR2(6) NOT NULL, 
  NOMBRE_CIUDAD_RESIDENCIA VARCHAR2(100), 
  PROFESOR_POLICIAL CHARACTER(1), 
  TIPO_VINCULACION NUMBER, 
  FUNCION_INVESTIGADOR VARCHAR2(512), 
  NIVEL_FORMACION NUMBER, 
  AREA_SABER NUMBER, 
  TITULO_OBTENIDO VARCHAR2(100), 
  FECHA_FINALIZACION_CARRERA DATE, 
  CONSTRAINT INVESTIGADOR_PK PRIMARY KEY (ID_INVESTIGADOR),
  CONSTRAINT INVESTIGADOR_UK1 UNIQUE (NUMERO_IDENTIFICACION),
  CONSTRAINT INVESTIGADOR_AREA_SABER_FK FOREIGN KEY (AREA_SABER) REFERENCES CONSTANTES (ID_CONSTANTES),
  CONSTRAINT INVESTIGADOR_FORMACION_FK FOREIGN KEY (NIVEL_FORMACION) REFERENCES CONSTANTES (ID_CONSTANTES),
  CONSTRAINT INVESTIGADOR_VINCULACION_FK FOREIGN KEY (TIPO_VINCULACION) REFERENCES CONSTANTES (ID_CONSTANTES)
);

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('147','TIPO_INFORME_AVANCE','Inicial','Inicial');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('148','TIPO_INFORME_AVANCE','Avance','Avance');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('149','TIPO_INFORME_AVANCE','Final','Final');

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('150','TIPO_INDICADORES_GENERALES_PROYECTO_CU_07','Consumo de horas del proyecto','Horas de investigación consumidas / Horas totales  proyectadas');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('151','TIPO_INDICADORES_GENERALES_PROYECTO_CU_07','Consumo de presupuesto','Presupuesto consumido / Total presupuesto');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (155, 'AREA_SABER_INVESTIGADOR', 'Matemáticas', 'Matemáticas');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (156, 'AREA_SABER_INVESTIGADOR', 'Ingeniería', 'Ingeniería');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (157, 'AREA_SABER_INVESTIGADOR', 'Medicina', 'Medicina');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (158, 'AREA_SABER_INVESTIGADOR', 'Ambiental', 'Ambiental');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (161, 'NIVEL_FORMACION_INVESTIGADOR', 'Pregrado', 'Pregrado');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (162, 'NIVEL_FORMACION_INVESTIGADOR', 'Postgrado', 'Postgrado');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (163, 'NIVEL_FORMACION_INVESTIGADOR', 'Especialización', 'Especialización');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (164, 'NIVEL_FORMACION_INVESTIGADOR', 'Maestría', 'Maestría');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (165, 'NIVEL_FORMACION_INVESTIGADOR', 'Doctorado', 'Doctorado');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (169, 'OPCIONES_SI_NO', 'Sí', 'Sí');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (170, 'OPCIONES_SI_NO', 'No', 'No');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (171, 'TIPO_PUBLICACION_INVESTIGADOR', 'Artículo en revista', 'Artículo en revista');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (172, 'TIPO_PUBLICACION_INVESTIGADOR', 'Artículo en revista indexada', 'Artículo en revista indexada');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (173, 'TIPO_PUBLICACION_INVESTIGADOR', 'Libro', 'Libro');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (174, 'TIPO_PUBLICACION_INVESTIGADOR', 'Capítulo en libro', 'Capítulo en libro');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (175, 'TIPO_PUBLICACION_INVESTIGADOR', 'Otro', 'Otro');

UPDATE OPCION_MENU SET TIPO_ACCESO='PRIVADO' WHERE ID_OPCION_MENU = 4;
Insert into OPCION_MENU (ID_OPCION_MENU,NOMBRE,TIPO_ACCESO,ACCION,ID_OPCION_MENU2,ORDEN,TITULO) values ('20','Registrar  investigador','PRIVADO','BEAN:#{cuIv01GestionarInvestigadoresFaces.initReturnCU}','4','5','Permite la creación y modificación de la información de investigadores que se encuentran vinculados con la VICIN');

Insert into ROL_OPCION_MENU (ID_ROL_OPCION_MENU,ID_ROL,ID_OPCION_MENU) values ('15','4','4');
Insert into ROL_OPCION_MENU (ID_ROL_OPCION_MENU,ID_ROL,ID_OPCION_MENU) values ('16','5','20');

INSERT INTO CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) VALUES (141,'INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Artículo en revista','Artículo en revista');
INSERT INTO CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) VALUES (142,'INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Prototipo','Prototipo');
INSERT INTO CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) VALUES (143,'INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Cartilla','Cartilla');
INSERT INTO CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) VALUES (144,'INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Manual','Manual');
INSERT INTO CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) VALUES (145,'INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Protocolo','Protocolo');
INSERT INTO CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) VALUES (146,'INFORME_AVANCE_FINAL_TIPO_PRODUCTO','Otro','Otro');

commit;
