ALTER TABLE PROYECTO ADD ID_PROPUESTA_NECESIDAD NUMBER;
ALTER TABLE PROYECTO ADD CONSTRAINT ID_PRO_NECES_PROPUESTA_NEC_FK FOREIGN KEY (ID_PROPUESTA_NECESIDAD) REFERENCES PROPUESTA_NECESIDAD (ID_PROPUESTA_NECESIDAD);

ALTER TABLE PROYECTO ADD ID_PROPUESTA_CONVOCATORIA NUMBER;
ALTER TABLE PROYECTO ADD CONSTRAINT ID_PRO_CONVOC_PROYECTO_FK FOREIGN KEY (ID_PROPUESTA_CONVOCATORIA) REFERENCES PROYECTO (ID_PROYECTO);

ALTER TABLE COMENTARIO ADD IDENTIFICACION VARCHAR2(100);

DROP TABLE INDICADORES_PROYECTO CASCADE CONSTRAINT;
CREATE TABLE INDICADORES_PROYECTO
  (
    ID_INDICADOR_PROYECTO NUMBER NOT NULL ,
    NOMBRE_INDICADOR      VARCHAR2(100),
    NOMBRE_NUMERADOR      VARCHAR2(50) NOT NULL ,
    NOMBRE_DENOMINADOR    VARCHAR2(50) NOT NULL ,
    FECHA_REGISTRO TIMESTAMP NOT NULL ,
    ID_USUARIO_ROL NUMBER NOT NULL ,
    ID_PROYECTO    NUMBER NOT NULL ,
    CONSTRAINT INDICADORES_PROYECTO_PK PRIMARY KEY (ID_INDICADOR_PROYECTO),
    CONSTRAINT INDICADORES_PROYECTO_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT INDICADORES_USUARIOROL_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL)	
  );

ALTER TABLE INDICADORES_PROYECTO  ADD INDICADOR_BASE CHAR(1) DEFAULT 'N';

CREATE SEQUENCE SEC_INDICADORES_PROYECTO
  START WITH 1
  INCREMENT by 1
  MINVALUE 1
;

CREATE SEQUENCE SEC_COMPROMISO_PROYECTO
  START WITH 1
  INCREMENT by 1
  MINVALUE 1
;

drop table COMPROMISO_PROYECTO cascade constraint;
CREATE TABLE COMPROMISO_PROYECTO
  (
    ID_COMPROMISO_PROYECTO  NUMBER NOT NULL ,
    ID_COMPROMISO_PERIODO   NUMBER NOT NULL ,
    ID_PROYECTO             NUMBER NOT NULL ,
    ESTADO                  NUMBER NOT NULL ,
    USUARIO_REGISTRO        VARCHAR2(50),
    ID_USUARIO_ROL_REGISTRA NUMBER,
    FECHA_CREACION TIMESTAMP (6),
    ID_USUARIO_ROL_ACT NUMBER,
    USUARIO_ACTUALIZA  VARCHAR2(50),
    FECHA_ACTUALIZACION TIMESTAMP (6),
    MAQUINA VARCHAR2(50),
    CONSTRAINT COMPROMISO_PROYECTO_PK PRIMARY KEY (ID_COMPROMISO_PROYECTO),
    CONSTRAINT COMPROMISO_PROYECTO_FK1 FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO) ,
    CONSTRAINT COMPROMISO_PROYECTO_FK2 FOREIGN KEY (ID_COMPROMISO_PERIODO) REFERENCES COMPROMISO_PERIODO (ID_COMPROMISO_PERIODO) ,
    CONSTRAINT COMPROMISO_PROYECTO_FK3 FOREIGN KEY (ESTADO) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT COMPROMISO_R_USUARIOROL_FK FOREIGN KEY (ID_USUARIO_ROL_REGISTRA) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) ,
    CONSTRAINT COMPROMISO_A_USUARIOROL_FK FOREIGN KEY (ID_USUARIO_ROL_ACT) REFERENCES USUARIO_ROL (ID_USUARIO_ROL)		
  );
COMMENT ON COLUMN COMPROMISO_PROYECTO.ID_COMPROMISO_PROYECTO
IS
  'Identificador compromiso proyecto';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.ID_COMPROMISO_PERIODO
IS
  'Identificador del compromiso del proyecto';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.ID_PROYECTO
IS
  'Identificador del proyecto';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.ESTADO
IS
  'Identificador estado de compromiso';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.USUARIO_REGISTRO
IS
  'Usuario registro';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.ID_USUARIO_ROL_REGISTRA
IS
  'Identificador usuario rol';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.ID_USUARIO_ROL_ACT
IS
  'Identificado de usuario que actualiza';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.USUARIO_ACTUALIZA
IS
  'Usuario que actualiza';
  COMMENT ON COLUMN COMPROMISO_PROYECTO.MAQUINA
IS
  'Maquina donde se genera el registro';

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('130','TIPO_INDICADORES_GENERALES_PROYECTO','Consumo de horas del proyecto','Horas invertidas en el proyecto / Total Horas del Proyecto');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('131','TIPO_INDICADORES_GENERALES_PROYECTO','Consumo de presupuesto','Presupuesto consumido / Presupuesto proyectado');

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('135','TIPO_GASTO_EVENTO_RELACIONADO','Promoción','Promoción');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('136','TIPO_GASTO_EVENTO_RELACIONADO','Organización','Organización');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('137','TIPO_GASTO_EVENTO_RELACIONADO','Sede y logística','Sede y logística');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('138','TIPO_GASTO_EVENTO_RELACIONADO','Comunicaciones','Comunicaciones');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('139','TIPO_GASTO_EVENTO_RELACIONADO','Pasajes y viáticos','Pasajes y viáticos');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('140','TIPO_GASTO_EVENTO_RELACIONADO','Transporte terrestre','Transporte terrestre');

commit;