CREATE TABLE RESPONSABLE_ACTIVIDAD_IMPLEMEN
  (
    ID_RESPONSABLE_ACTIVIDAD_IMPL NUMBER NOT NULL ,
    ID_PERSONAL_IMPLEMENTACION NUMBER NOT NULL ,
    ID_ACTIVIDAD_IMPLEMENTACION  NUMBER NOT NULL,    
    CONSTRAINT RESPONSABLE_ACTIVIDAD_IMPL_PK PRIMARY KEY (ID_RESPONSABLE_ACTIVIDAD_IMPL), 
    CONSTRAINT FK_ID_PERSO_IMPLE_PERSON_IMPL FOREIGN KEY (ID_PERSONAL_IMPLEMENTACION) REFERENCES PERSONAL_IMPLEMENTACION (ID_PERSONAL_IMPLEMENTACION),
    CONSTRAINT FK_ID_ACTVI_ACTI_IMPLEMEN FOREIGN KEY (ID_ACTIVIDAD_IMPLEMENTACION) REFERENCES ACTIVIDADES_IMPLEMENTACION (ID_ACTIVIDAD_IMPLEMENTACION)	
  );
  
CREATE SEQUENCE SEC_RESPONSABLE_ACTIVIDAD_IMPL
  INCREMENT by 1
  MINVALUE 1
;

CREATE SEQUENCE SEC_ACTIVIDAD_IMPLEMENTACION
  INCREMENT by 1
  MINVALUE 1;


ALTER TABLE ENSAYO_CRITICO 
ADD (FECHA_PRESENTACION DATE );

INSERT INTO CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION, NOMBRE_CRITERIO, DESCRIPCION_CRITERIO, VALOR, TIPO, ESTADO) VALUES (4, 'Solución al problema de investigación', 'Solución al problema de investigación', 30, 'ENSAYO_CRITICO', 'ACTIVO');
INSERT INTO CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION, NOMBRE_CRITERIO, DESCRIPCION_CRITERIO, VALOR, TIPO, ESTADO) VALUES (5, 'Cumplimiento de objetivos', 'Cumplimiento de objetivos', 40, 'ENSAYO_CRITICO', 'ACTIVO');  
INSERT INTO CRITERIO_EVALUACION (ID_CRITERIO_EVALUACION, NOMBRE_CRITERIO, DESCRIPCION_CRITERIO, VALOR, TIPO, ESTADO) VALUES (6, 'Claridad conceptual', 'Claridad conceptual', 30, 'ENSAYO_CRITICO', 'ACTIVO');  

ALTER TABLE EVALUACION_PROYECTO 
ADD (ID_ENSAYO_CRITICO NUMBER );

ALTER TABLE EVALUACION_PROYECTO 
ADD (VALOR_CRITERIO_VICIN VARCHAR2(20) );

ALTER TABLE EVALUACION_PROYECTO  
MODIFY (ID_PROYECTO NULL);

ALTER TABLE EVALUACION_PROYECTO ADD CONSTRAINT ENSAYO_CRITICO_FK FOREIGN KEY (ID_ENSAYO_CRITICO) REFERENCES ENSAYO_CRITICO (ID_ENSAYO_CRITICO)
ON DELETE CASCADE ENABLE;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (212,'TIPO_ESTADO_EVALUACION_UNIDAD_ENSAYO','No aprobado en la Unidad','No aprobado en la Unidad');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (213,'TIPO_ESTADO_EVALUACION_UNIDAD_ENSAYO','Aprobado','Aprobado');

INSERT INTO OPCION_MENU (ID_OPCION_MENU, NOMBRE, TIPO_ACCESO, ACCION, ID_OPCION_MENU2, ORDEN, TITULO)
    VALUES (26, 'Consultar investigadores', 'PRIVADO', 'BEAN:#{cuIv02ConsultarInvestigadores.initReturnCU}', 4, 1, 
        'Permite al usuario consultar la información del investigador.');
INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES (33, 21, 26);

ALTER TABLE ENSAYO_CRITICO ADD (ID_CALIFICACION_CUCO8 NUMBER );
ALTER TABLE ENSAYO_CRITICO ADD (ID_CALIFICACION_CUCO10 NUMBER );
ALTER TABLE ENSAYO_CRITICO ADD CONSTRAINT CALIFICA_CONSTA_CO8_ENSAYO_FK FOREIGN KEY ( ID_CALIFICACION_CUCO8 ) REFERENCES CONSTANTES ( ID_CONSTANTES );
ALTER TABLE ENSAYO_CRITICO ADD CONSTRAINT CALIFICA_CONSTA_CO10_ENSAYO_FK FOREIGN KEY ( ID_CALIFICACION_CUCO10 ) REFERENCES CONSTANTES ( ID_CONSTANTES );

ALTER TABLE ENSAYO_CRITICO ADD (ID_ESTADO_CUCO8 NUMBER );
ALTER TABLE ENSAYO_CRITICO ADD (ID_ESTADO_CUCO10 NUMBER );
ALTER TABLE ENSAYO_CRITICO ADD CONSTRAINT ESTADO_CONSTA_CO8_ENSAYO_FK FOREIGN KEY ( ID_ESTADO_CUCO8 ) REFERENCES CONSTANTES ( ID_CONSTANTES );
ALTER TABLE ENSAYO_CRITICO ADD CONSTRAINT ESTADO_CONSTA_CO10_ENSAYO_FK FOREIGN KEY ( ID_ESTADO_CUCO10 ) REFERENCES CONSTANTES ( ID_CONSTANTES );

ALTER TABLE ENSAYO_CRITICO DROP CONSTRAINT ENSAYO_CRITICO_CONSTANTE_FK;
ALTER TABLE ENSAYO_CRITICO DROP COLUMN ESTADO_ENSAYO;

ALTER TABLE PROPUESTA_NECESIDAD ADD ROL_ACTUAL VARCHAR2(30);

CREATE TABLE CORREO_PARAMETRIZA
  (
    CODIGO VARCHAR2(50) NOT NULL ,
    ASUNTO VARCHAR2(512) NOT NULL ,
    TEXTO BLOB NOT NULL ,
    CONSTRAINT CORREO_PARAMETRIZA_PK PRIMARY KEY (CODIGO)
  );

CREATE TABLE CORREO_ENVIO
(
    ID NUMBER NOT NULL ,
    CODIGO VARCHAR2(50) NOT NULL ,
    ASUNTO VARCHAR2(512) NOT NULL ,
    TEXTO BLOB NOT NULL ,	
    ESTADO VARCHAR2(20) NOT NULL ,
    CONSTRAINT CORREO_ENVIO_PK PRIMARY KEY (ID)
  );

CREATE SEQUENCE SEC_CORREO_ENVIO
  INCREMENT by 1
  MINVALUE 1;

CREATE SEQUENCE SEC_EVALUADORES_PROYECTO_GRADO
  INCREMENT by 1
  MINVALUE 1;

DROP TABLE EVALUACION_PROYECTO_GRADO CASCADE CONSTRAINTS;
CREATE TABLE EVALUACION_PROYECTO_GRADO
  (
    ID_EVALUACION_PROY_GRADO NUMBER NOT NULL ,
    FECHA_SUSTENTACION DATE,
    NOTA_TRABAJO      NUMBER(5,2),
    NOTA_SUSTENTACION NUMBER(5,2) NOT NULL ,
    NOTA_FINAL        NUMBER(5,2),
    ID_PROYECTO       NUMBER NOT NULL ,
    FECHA_REGISTRO TIMESTAMP NOT NULL ,
    ID_USUARIO_ROL NUMBER,
    MAQUINA        VARCHAR2(256) NOT NULL ,
    CONSTRAINT EVALUACION_PROYECTO_GRADO_PK PRIMARY KEY (ID_EVALUACION_PROY_GRADO),
    CONSTRAINT EVAL_PROY_GRADO_PROYECTO_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO), 
    CONSTRAINT EVAL_PROY_ROLUSUARIO_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) 
  );

CREATE SEQUENCE SEC_EVALUACION_PROYECTO_GRADO
  INCREMENT by 1
  MINVALUE 1;

ALTER TABLE CORREO_ENVIO ADD (DETALLEFALLO BLOB);
ALTER TABLE CORREO_ENVIO ADD (FECHA TIMESTAMP);
ALTER TABLE CORREO_ENVIO ADD (CORREO VARCHAR(200) );

drop table correo_envio cascade constraint ;
drop table correo_parametriza cascade constraint ;

CREATE TABLE CORREO_ENVIO
  (
    ID     NUMBER NOT NULL ,
    CODIGO VARCHAR2(50 ) NOT NULL ,
    ASUNTO VARCHAR2(512 ) NOT NULL ,
    TEXTO BLOB NOT NULL ,
    ESTADO VARCHAR2(20 ) NOT NULL ,
    DETALLEFALLO BLOB,
    FECHA TIMESTAMP (6),
    CORREO VARCHAR2(200 ),
    CONSTRAINT CORREO_ENVIO_PK PRIMARY KEY (ID) 
  );
  
   CREATE TABLE CORREO_PARAMETRIZA
  (
    CODIGO VARCHAR2(50 ) NOT NULL ,
    ASUNTO VARCHAR2(512 ) NOT NULL ,
    TEXTO BLOB ,
    FORMATO VARCHAR2(50 ),
    CONSTRAINT CORREO_PARAMETRIZA_PK PRIMARY KEY (CODIGO)
  );
  
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_NE_01_PERIODO_PUBLICADO','Solicitud temas de investigación institucional','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_NE_02_JEFES_UNIDAD','Envío de propuestas para revisión','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_NE_05_ENVIO_PROPUESTA_VICIN','Envío de propuestas de necesidades de la Unidad.','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_NE_05_PROPUESTAS_NO_ACEPTADAS','Propuestas no aceptadas que necesitan correcciones.','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_NE_06_RESULTADO_REVISION','Resultado de la revisión de propuestas.','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_CO_01_PUBLICACION_CONVOCATORIA','Convocatoria N° {_parametro1_} {_parametro2_}','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_CO_02_ENVIO_PROPUESTA_REVISION','Envío de propuestas para revisión','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_PR_01_FORMULARIO_JEFE_UNIDAD','Envío de la formulación del proyecto de investigación para revisión','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_CO_03_JEFE_UNIDAD_NOACEPTA_PROPUESTA','Propuesta no aceptada para convocatoria','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_CO_03_JEFE_UNIDAD_ENVIA_PROP_CONVOCATO_VICIN','Envío de propuestas de convocatoria','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_CO_04_PUBLICAR_RESULTADOS','Publicación de resultados de la convocatoria por financiación','text/html; charset=utf-8');
Insert into CORREO_PARAMETRIZA (CODIGO,ASUNTO,FORMATO) values ('CU_PR_07_ENVIO_COMPROMISO_INFORME','Envío informe de avance del proyecto de investigación para revisión','text/html; charset=utf-8');


DROP TABLE ASESORIA_PROYECTO CASCADE CONSTRAINTS;
CREATE TABLE ASESORIA_PROYECTO
  (
    ID_ASESORIA_PROYECTO NUMBER NOT NULL ,
    RESULTADO_ASESORIA   VARCHAR2(4000),
    ID_PROYECTO    NUMBER NOT NULL ,
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    ID_USUARIO_ROL NUMBER NOT NULL,
    MAQUINA        VARCHAR2(40 ) NOT NULL,    
    CONSTRAINT ASESORIA_PROYECTO_PK PRIMARY KEY (ID_ASESORIA_PROYECTO),
    CONSTRAINT ASESORIAP_PROYECTO_FK FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO), 
    CONSTRAINT ASESORIAP_ROLUSUARIO_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) 
  );
COMMENT ON COLUMN ASESORIA_PROYECTO.ID_ASESORIA_PROYECTO
IS
  'Identificador único';
  COMMENT ON COLUMN ASESORIA_PROYECTO.RESULTADO_ASESORIA
IS
  'Resultado Asesoría';
  COMMENT ON COLUMN ASESORIA_PROYECTO.FECHA_REGISTRO
IS
  'Fecha de registro';
  COMMENT ON COLUMN ASESORIA_PROYECTO.ID_USUARIO_ROL
IS
  'Usuario Rol que generó el registro';
  COMMENT ON COLUMN ASESORIA_PROYECTO.MAQUINA
IS
  'Máquina donde se originó la solicitud';
  COMMENT ON COLUMN ASESORIA_PROYECTO.ID_PROYECTO
IS
  'Identificador del proyecto';
  
  
  
  DROP TABLE MODALIDAD_ASESORIA_PROYECTO CASCADE CONSTRAINTS;
  CREATE TABLE MODALIDAD_ASESORIA_PROYECTO
  (
    ID_MODALIDAD_PROYECTO NUMBER NOT NULL ,
    ID_TIPO_MODALIDAD       NUMBER,
    ID_USUARIO_ROL       NUMBER NOT NULL ,
    ID_ASESORIA_PROYECTO NUMBER NOT NULL ,
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    CONSTRAINT MODALIDAD_ASESORIA_PROYECTO_PK PRIMARY KEY (ID_MODALIDAD_PROYECTO),
    CONSTRAINT MODALID_ASEPRO_CONSTANTES_FK FOREIGN KEY (ID_TIPO_MODALIDAD) REFERENCES CONSTANTES (ID_CONSTANTES) 
  );
  
COMMENT ON COLUMN MODALIDAD_ASESORIA_PROYECTO.FECHA_REGISTRO
IS
  'Fecha de registro';
  COMMENT ON COLUMN MODALIDAD_ASESORIA_PROYECTO.ID_TIPO_MODALIDAD
IS
  'Tipo de modalidad Virtual, Presencial, Telefonica, Otros';
  COMMENT ON COLUMN MODALIDAD_ASESORIA_PROYECTO.ID_USUARIO_ROL
IS
  'Identificador de usuario rol que hace la modalidad asesoría del proyecto';

CREATE SEQUENCE SEC_MODALIDAD_ASESORIA_PROYE
  INCREMENT by 1
  MINVALUE 1;

CREATE SEQUENCE SEC_ASESORIA_PROYECTO
  INCREMENT by 1
  MINVALUE 1;

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (214, 'TIPO_ESTADO_VINCULACION_INVESTIGADOR', 'Vinculado actualmente', 'Vinculado actualmente');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (215, 'TIPO_ESTADO_VINCULACION_INVESTIGADOR', 'No vinculado actualmente', 'No vinculado actualmente');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (216, 'TIPO_CARACTERISTICAS_INVESTIGADOR', 'Con publicaciones', 'Con publicaciones');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (217, 'TIPO_CARACTERISTICAS_INVESTIGADOR', 'Con investigaciones en otras instituciones', 'Con investigaciones en otras instituciones');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (218, 'TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO', 'Virtual', 'Virtual');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (219, 'TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO', 'Presencial', 'Presencial');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (220, 'TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO', 'Telefonica', 'Telefónica');
INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR) VALUES (221, 'TIPO_MODALIDADES_ASESORIAS_TRABAJO_DE_GRADO', 'Otros', 'Otros');

ALTER TABLE COMENTARIO_PROYECTO 
ADD (AUTOR_COMENTARIO NUMBER );

ALTER TABLE COMENTARIO_PROYECTO ADD CONSTRAINT AUTOR_COMENTARIO_CONSTANTE_FK FOREIGN KEY (AUTOR_COMENTARIO)
REFERENCES CONSTANTES (ID_CONSTANTES) ON DELETE CASCADE ENABLE;


Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (222,'TIPO_ESTADO_EVALUACION_VICIN_ENSAYO','No aprobado','No aprobado');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (223,'TIPO_ESTADO_EVALUACION_VICIN_ENSAYO','Ganador','Ganador');

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (224,'TIPO_AUTOR_COMENTARIO_EVALUACION_ENSAYO','VICIN','VICIN');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (225,'TIPO_AUTOR_COMENTARIO_EVALUACION_ENSAYO','Jefe de Unidad','Jefe de Unidad');

INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES ('35', '23', '5');
INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES ('36', '23', '21');

INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES ('39', '30', '5');
INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES ('40', '30', '21');

INSERT INTO USUARIO_ROL (ID_USUARIO_ROL, IDENTIFICADOR_USUARIO, ID_ROL) VALUES ('36', '123', '30');

ALTER TABLE EVALUADORES_PROYECTO_GRADO  MODIFY (TELEFONO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (RESUMEN_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (PALABRAS_CLAVE_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (ABSTRACT_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (KEYWORDS_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (INTRODUCCION_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (DESARROLLO_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (NOMBRE_ARCHIVO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (NOMBRE_ARCHIVO_ORIGINAL NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (CONCLUSIONES_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (PROPUESTA_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (BIBLIOGRAFIA_ENSAYO NULL);

ALTER TABLE ENSAYO_CRITICO  
MODIFY (ID_USUARIO_ROL_CREACION NULL);


ALTER TABLE ENSAYO_CRITICO  
MODIFY (NOMBRE_ARCHIVO NULL);

ALTER TABLE ENSAYO_CRITICO  ADD USUARIO VARCHAR2(50);
ALTER TABLE ENSAYO_CRITICO  ADD IDENTIFICACION VARCHAR2(50);
ALTER TABLE VISTA_FUNCIONARIO  ADD GRADO_ALFABETICO VARCHAR2(5);

ALTER TABLE INVESTIGADORES_PROYECTO  ADD ORIGEN_SIAF_O_INVESTI CHAR(1) DEFAULT 'S';
COMMENT ON COLUMN INVESTIGADORES_PROYECTO.FECHA_REGISTRO IS 'Campo que indica de donde fue originado el investigador (TABLA): S=SIAF_o_VISTAFUNCIONARIO, I=INVESTIGADOR';

CREATE SEQUENCE SEC_NIVACA_VICIN_DINAE
  INCREMENT by 1
  MINVALUE 1;



CREATE TABLE T_NIVACA_VICIN_DINAE(ID_FORMACION_INV NUMBER ,IDENTIFICACION VARCHAR2(100), TITULO VARCHAR2(200), NIVEL_ACADEMICO VARCHAR2(200), FECHA_TERMINO TIMESTAMP)

INSERT INTO  T_NIVACA_VICIN_DINAE (  select SEC_NIVACA_VICIN_DINAE.NEXTVAL, 
  v.identificacion, 
  'TITULO_'|| to_char(SEC_NIVACA_VICIN_DINAE.currval), 
  'NIVEL_ACADEMICO_'|| to_char(SEC_NIVACA_VICIN_DINAE.currval),
  sysdate 
from vista_funcionario v); 

CREATE OR REPLACE FORCE VIEW NIVACA_VICIN_DINAE (ID_FORMACION_INV,IDENTIFICACION, TITULO, NIVEL_ACADEMICO, FECHA_TERMINO) AS 
  SELECT ID_FORMACION_INV,IDENTIFICACION, TITULO, NIVEL_ACADEMICO, FECHA_TERMINO
from T_NIVACA_VICIN_DINAE;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (229,'OTROS_GASTOS_RUBROS','Bibliografía y documentación','Bibliografía y documentación');

drop table INDICADOR_COMPROMISO_PROYECTO cascade constraint;
CREATE TABLE INDICADOR_COMPROMISO_PROYECTO
  (
    ID_INDICADOR_COMPROMISO_PROYEC   NUMBER NOT NULL ,
    VALOR_NUMERADOR    NUMBER NOT NULL ,
    VALOR_DENOMINADOR  NUMBER NOT NULL ,
	ID_INDICADOR_PROYECTO  NUMBER NOT NULL ,
    ID_COMPROMISO_PROYECTO NUMBER NOT NULL ,    
    FECHA_REGISTRO TIMESTAMP NOT NULL,
	ID_USUARIO_ROL       NUMBER NOT NULL ,
	FECHA_MODIFICA TIMESTAMP,
    CONSTRAINT INDICADOR_COMPROMISO_PROYEC_PK PRIMARY KEY (ID_INDICADOR_COMPROMISO_PROYEC),
    CONSTRAINT ID_INDICA_PROY_INDICADORPRO_FK FOREIGN KEY (ID_INDICADOR_PROYECTO) REFERENCES INDICADORES_PROYECTO (ID_INDICADOR_PROYECTO) ,
    CONSTRAINT ID_COMPROMO_COMPROMIPRO_FK FOREIGN KEY (ID_COMPROMISO_PROYECTO) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO),
	CONSTRAINT ID_USUARIO_USUARIOROL_FK FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) 
  );

CREATE SEQUENCE SEC_INDICADOR_COMPROMI_PROYEC
  INCREMENT by 1
  MINVALUE 1;


Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('233','TIPO_ESTADO_RESULTADO_COMPROMISO_PROYECTO','Aceptado','Aceptado');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('234','TIPO_ESTADO_RESULTADO_COMPROMISO_PROYECTO','No Aceptado','No Aceptado');

ALTER TABLE COMPROMISO_PROYECTO ADD ID_RESULTADO_VICIN NUMBER;
ALTER TABLE COMPROMISO_PROYECTO ADD CONSTRAINT ID_RESULTADOVICIN_CONSTANTE_FK FOREIGN KEY (ID_RESULTADO_VICIN) REFERENCES CONSTANTES (ID_CONSTANTES);

drop sequence SEC_COMPROMISO_IMPLEMENTACION;
CREATE SEQUENCE SEC_COMPROMISO_IMPLEMENTACION
  INCREMENT by 1
  MINVALUE 1;

drop table COMPROMISO_IMPLEMENTACION cascade constraints;
 CREATE TABLE COMPROMISO_IMPLEMENTACION
  (
    ID_COMPROMISO_IMPLEMENTACION NUMBER NOT NULL ,
    ID_IMPLEMENTACION_PROY       NUMBER NOT NULL ,
    ID_TIPO_COMPROMISO           NUMBER NOT NULL ,
    ID_ESTADO_COMPROMISO_IMPL    NUMBER NOT NULL ,
    USUARIO                      VARCHAR2(50 ),
    FECHA_CREACION DATE,
    ID_USUARIO_ROL NUMBER,
    MAQUINA        VARCHAR2(50 ),
    FECHA_ACTUALIZACION DATE,
    ID_USUARIO_ROL_ACTUALIZA NUMBER,
    USUARIO_ACTUALIZA        VARCHAR2(50 ),
    MAQUINA_ACTUALIZA        VARCHAR2(50 ),
    CONSTRAINT COMPROMISO_IMPLEMENTACION_PK PRIMARY KEY (ID_COMPROMISO_IMPLEMENTACION),
    CONSTRAINT COMPR_IML_UROL_FK2 FOREIGN KEY (ID_USUARIO_ROL_ACTUALIZA) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) ,
    CONSTRAINT COMPR_IMPL_ESTADO_COMPR_FK2 FOREIGN KEY (ID_ESTADO_COMPROMISO_IMPL) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT COMPR_IMPL_TIPO_COMPR_FK1 FOREIGN KEY (ID_TIPO_COMPROMISO) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT COMPR_IMPL_UROL_FK1 FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) 
  );
COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_COMPROMISO_IMPLEMENTACION
IS
  'Identificador del compromiso implementación';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_IMPLEMENTACION_PROY
IS
  'Identificador de la implementación de proyecto';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_TIPO_COMPROMISO
IS
  'Tipo compromiso de implematación (Plan de trabajo, Informe de avance Implementación, Informe Final Implementación';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_ESTADO_COMPROMISO_IMPL
IS
  'Identificador del estado del compromiso de implementación';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.USUARIO
IS
  'Login del usuario que realiza el registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.FECHA_CREACION
IS
  'Fecha de creación del registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_USUARIO_ROL
IS
  'Identificador del usuario rol que registra el compromiso';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.MAQUINA
IS
  'Máquina donde se origina el registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.FECHA_ACTUALIZACION
IS
  'Fecha de actualización del registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_USUARIO_ROL_ACTUALIZA
IS
  'Usuario rol que actualiza el registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.USUARIO_ACTUALIZA
IS
  'Usuario que realiza la actualización del registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.MAQUINA_ACTUALIZA
IS
  'Maquina desde se origina la actualización';

ALTER TABLE COMPROMISO_IMPLEMENTACION ADD ID_RESULTADO_VICIN NUMBER;
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD CONSTRAINT ID_RESULTADO_CIMPL_CONSTAN_FK FOREIGN KEY (ID_RESULTADO_VICIN) REFERENCES CONSTANTES (ID_CONSTANTES);

drop table COMENTARIO_COMPROMISO_PROYECTO cascade constraints;
CREATE TABLE COMENTARIO_COMPROMISO_PROYECTO
  (
    ID_COMENTARIO_COMPROMISO_PROYE NUMBER NOT NULL ,
    ID_COMPROMISO_PROYECTO      NUMBER,
    ID_COMPROMISO_IMPLEMENTACION      NUMBER,
    FECHA_REGISTRO TIMESTAMP NOT NULL ,
    COMENTARIO     VARCHAR2(512 ),
    ID_USUARIO_ROL NUMBER NOT NULL ,
    IDENTIFICACION            VARCHAR2(100) NOT NULL ,
	USUARIO          VARCHAR2(100) NOT NULL ,
    NOMBRE_COMPLETO           VARCHAR2(200) NOT NULL ,
    CONSTRAINT COMENTARIO_COMPROMISO_PROYE_PK PRIMARY KEY (ID_COMENTARIO_COMPROMISO_PROYE),
	CONSTRAINT ID_COMPRO_PROYE_COMCCOMPRO_FK FOREIGN KEY (ID_COMPROMISO_PROYECTO) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO) ,
	CONSTRAINT ID_COMPRO_IMPL_COMCCOMPRO_FK FOREIGN KEY (ID_COMPROMISO_IMPLEMENTACION) REFERENCES COMPROMISO_IMPLEMENTACION (ID_COMPROMISO_IMPLEMENTACION) 
  );

CREATE SEQUENCE SEC_COMENTARIO_COMPROMISO_PROY
  INCREMENT by 1
  MINVALUE 1;

ALTER TABLE COMPROMISO_IMPLEMENTACION ADD COMENTARIO_TEMPORAL VARCHAR2(512);
ALTER TABLE COMPROMISO_PROYECTO ADD COMENTARIO_TEMPORAL VARCHAR2(512);


/*CREATE SEQUENCE SEC_TEMPORAL_ELIMINAR
  INCREMENT by 1
  MINVALUE 1;*/
--insert into grados_valores select SEC_TEMPORAL_ELIMINAR.NEXTVAL,GRADO,VALOR_HORA,2014 from grados_valores;

DROP TABLE COMPROMISO_IMPLEMENTACION CASCADE CONSTRAINTS;
CREATE TABLE COMPROMISO_IMPLEMENTACION
  (
    ID_COMPROMISO_IMPLEMENTACION NUMBER NOT NULL ,
    ID_IMPLEMENTACION_PROY       NUMBER NOT NULL ,
    ID_TIPO_COMPROMISO           NUMBER NOT NULL ,
    ID_ESTADO_COMPROMISO_IMPL    NUMBER NOT NULL ,
    USUARIO                      VARCHAR2(50 ),
    FECHA_CREACION DATE,
    ID_USUARIO_ROL NUMBER,
    MAQUINA        VARCHAR2(50 ),
    FECHA_ACTUALIZACION DATE,
    ID_USUARIO_ROL_ACTUALIZA NUMBER,
    USUARIO_ACTUALIZA        VARCHAR2(50 ),
    MAQUINA_ACTUALIZA        VARCHAR2(50 ),
    ID_RESULTADO_VICIN       NUMBER,
    COMENTARIO_TEMPORAL      VARCHAR2(512 ),
    CONSTRAINT COMPROMISO_IMPLEMENTACION_PK PRIMARY KEY (ID_COMPROMISO_IMPLEMENTACION),
    CONSTRAINT COMPR_IML_UROL_FK2 FOREIGN KEY (ID_USUARIO_ROL_ACTUALIZA) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) ,
    CONSTRAINT COMPR_IMPL_ESTADO_COMPR_FK2 FOREIGN KEY (ID_ESTADO_COMPROMISO_IMPL) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT COMPR_IMPL_TIPO_COMPR_FK1 FOREIGN KEY (ID_TIPO_COMPROMISO) REFERENCES CONSTANTES (ID_CONSTANTES) ,
    CONSTRAINT COMPR_IMPL_UROL_FK1 FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL) ,
    CONSTRAINT ID_RESULTADO_CIMPL_CONSTAN_FK FOREIGN KEY (ID_RESULTADO_VICIN) REFERENCES CONSTANTES (ID_CONSTANTES),
	CONSTRAINT COMPR_IML_IMPL_PROY_FK2 FOREIGN KEY (ID_IMPLEMENTACION_PROY) REFERENCES IMPLEMENTACIONES_PROYECTO (ID_IMPLEMENTACION_PROY) 	
  );
COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_COMPROMISO_IMPLEMENTACION
IS
  'Identificador del compromiso implementación';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_IMPLEMENTACION_PROY
IS
  'Identificador de la implementación de proyecto';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_TIPO_COMPROMISO
IS
  'Tipo compromiso de implematación (Plan de trabajo, Informe de avance Implementación, Informe Final Implementación';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_ESTADO_COMPROMISO_IMPL
IS
  'Identificador del estado del compromiso de implementación';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.USUARIO
IS
  'Login del usuario que realiza el registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.FECHA_CREACION
IS
  'Fecha de creación del registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_USUARIO_ROL
IS
  'Identificador del usuario rol que registra el compromiso';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.MAQUINA
IS
  'Máquina donde se origina el registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.FECHA_ACTUALIZACION
IS
  'Fecha de actualización del registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.ID_USUARIO_ROL_ACTUALIZA
IS
  'Usuario rol que actualiza el registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.USUARIO_ACTUALIZA
IS
  'Usuario que realiza la actualización del registro';
  COMMENT ON COLUMN COMPROMISO_IMPLEMENTACION.MAQUINA_ACTUALIZA
IS
  'Maquina desde se origina la actualización';

DROP PUBLICACION_INVESTIGADOR CASCADE CONSTRAINTS;
CREATE TABLE PUBLICACION_INVESTIGADOR 
(
  ID_PUBLICACION_INVESTIGADOR NUMBER(6) NOT NULL, 
  ID_INVESTIGADOR NUMBER NOT NULL, 
  ID_TIPO_PUBLICACION NUMBER NOT NULL, 
  TITULO_PUBLICACION VARCHAR2(256) NOT NULL, 
  RESUMEN_PUBLICACION VARCHAR2(512), 
  FECHA_PUBLICACION DATE NOT NULL, 
  CODIGO_PAIS_PUBLICACION VARCHAR2(20), 
  NOMBRE_PAIS_PUBLICACION VARCHAR2(100), 
  CODIGO_ISSN VARCHAR2(20), 
  NOMBRE_REVISTA VARCHAR2(100), 
  VOLUMEN_REVISTA VARCHAR2(20), 
  FASCICULO_REVISTA VARCHAR2(20), 
  SERIE_REVISTA VARCHAR2(20), 
  PAGINA_INICIO_REVISTA NUMBER(6), 
  CODIGO_ISBN VARCHAR2(20), 
  NOMBRE_LIBRO VARCHAR2(100), 
  EDITORIAL_LIBRO VARCHAR2(100), 
  PAGINA_INICIO_LIBRO NUMBER(6), 
  CONSTRAINT PUBLICACION_INVESTIGADOR_PK PRIMARY KEY (ID_PUBLICACION_INVESTIGADOR),
  CONSTRAINT PUBLICACION_INVESTIGADOR_FK FOREIGN KEY (ID_INVESTIGADOR) REFERENCES INVESTIGADOR (ID_INVESTIGADOR),
  CONSTRAINT PUBLICACION_TIPO_FK FOREIGN KEY (ID_TIPO_PUBLICACION) REFERENCES CONSTANTES (ID_CONSTANTES)
);

CREATE SEQUENCE SEC_PUBLICACION_INVESTIGADOR INCREMENT BY 1 START WITH 1;