ALTER TABLE COMPROMISO_PROYECTO ADD (FECHA_COMPROMISO DATE);
ALTER TABLE COMPROMISO_PROYECTO ADD (ID_COMPROMISO_CORRECCION NUMBER);
ALTER TABLE COMPROMISO_PROYECTO ADD CONSTRAINT ID_COMPRO_CORRE_CONSTANTE_FK FOREIGN KEY (ID_COMPROMISO_CORRECCION) REFERENCES CONSTANTES (ID_CONSTANTES);
ALTER TABLE COMPROMISO_PROYECTO ADD (ID_COMPROMISO_PADRE NUMBER);
ALTER TABLE COMPROMISO_PROYECTO ADD CONSTRAINT ID_COMPRO_PADRE_IMPL_CONSTA_FK FOREIGN KEY (ID_COMPROMISO_PADRE) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO);
ALTER TABLE COMPROMISO_PROYECTO ADD (ID_COMPROMISO_HIJO NUMBER);
ALTER TABLE COMPROMISO_PROYECTO ADD CONSTRAINT ID_COMPRO_HIJO_IMPL_CONSTA_FK FOREIGN KEY (ID_COMPROMISO_HIJO) REFERENCES COMPROMISO_PROYECTO (ID_COMPROMISO_PROYECTO);

ALTER TABLE COMPROMISO_IMPLEMENTACION ADD (FECHA_COMPROMISO DATE);
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD (ID_COMPROMISO_CORRECCION NUMBER);
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD CONSTRAINT ID_COMP_CORR_IMPL_CONSTANTE_FK FOREIGN KEY (ID_COMPROMISO_CORRECCION) REFERENCES CONSTANTES (ID_CONSTANTES);
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD (ID_COMPROMISO_PADRE NUMBER);
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD CONSTRAINT ID_COMPIMP_PADRE_IMP_CONSTA_FK FOREIGN KEY (ID_COMPROMISO_PADRE) REFERENCES COMPROMISO_IMPLEMENTACION (ID_COMPROMISO_IMPLEMENTACION);
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD (ID_COMPROMISO_HIJO NUMBER);
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD CONSTRAINT ID_COMPIMP_HIJO_IMP_CONSTA_FK FOREIGN KEY (ID_COMPROMISO_HIJO) REFERENCES COMPROMISO_IMPLEMENTACION (ID_COMPROMISO_IMPLEMENTACION);

ALTER TABLE COMPROMISO_PROYECTO ADD (NOMBRE_COMPROMISO_CORRECCION VARCHAR2(100));
ALTER TABLE COMPROMISO_IMPLEMENTACION ADD (NOMBRE_COMPROMISO_CORRECCION VARCHAR2(100));

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('252','TIPO_COMPROMISO_CORRECCION','Pendiente corrección','Pendiente corrección');

-- cu-pr-12
INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU) VALUES ('50', '13', '3');
ALTER TABLE DETALLE_EVALUACION MODIFY (IDENTIFICACION_EVALUADOR VARCHAR2(20) );
CREATE SEQUENCE  SEC_DETALLE_EVALUACION  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;n
ALTER TABLE EVALUACION_PROYECTO MODIFY (VALOR_CRITERIO NULL);
