ALTER TABLE EJECUCION_EQUIPOS_PROYECTO
ADD CONSTRAINT EJECUCION_EQUIPOS_PROYECTO_FK1 FOREIGN KEY (ID_EQUIPO_INVESTIGACION)
REFERENCES EQUIPOS_INVESTIGACION (ID_EQUIPO_INVESTIGACION) 
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE SEC_EJECUCION_EQUIPOS_PROYECTO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999;

INSERT INTO OPCION_MENU (ID_OPCION_MENU, NOMBRE, TIPO_ACCESO, ORDEN)
VALUES (8, 'Administración', 'PRIVADO', 7);

INSERT INTO OPCION_MENU 
(ID_OPCION_MENU, NOMBRE, TIPO_ACCESO, ACCION, ID_OPCION_MENU2, ORDEN, TITULO)
VALUES (31, 'Administrar criterios de evaluación', 'PRIVADO', 'BEAN:#{cuAd03AdminCriteriosEvaluacion.initReturnCU}',
8, 3, 'Permite administrar los criterios de evaluación');

INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU)
VALUES (47, 2, 8);

INSERT INTO ROL_OPCION_MENU (ID_ROL_OPCION_MENU, ID_ROL, ID_OPCION_MENU)
VALUES (48, 2, 31);

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (245, 'TIPO_CRITERIO_EVALUACION_ADMINISTRAR', 'Convocatoria de financiación', 'Convocatoria de financiación');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (246, 'TIPO_CRITERIO_EVALUACION_ADMINISTRAR', 'Convocatoria de ensayo', 'Convocatoria de ensayo');

INSERT INTO CONSTANTES (ID_CONSTANTES, TIPO, CODIGO, VALOR)
VALUES (247, 'TIPO_CRITERIO_EVALUACION_ADMINISTRAR', 'Evaluación de proyecto', 'Evaluación de proyecto');


CREATE SEQUENCE SEC_EJECUCION_EVENTOS_PROYECTO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999;

ALTER TABLE EJECUCION_VIAJES_PROYECTO
ADD CONSTRAINT EJECUCION_VIAJES_PROYECTO_FK3 FOREIGN KEY (ID_VIAJE_PROYECTO) 
REFERENCES VIAJES_PROYECTO (ID_VIAJE_PROYECTO)
ON DELETE CASCADE ENABLE;

ALTER TABLE EJECUCION_VIAJES_PROYECTO RENAME COLUMN USUARIO_RREGISTRA TO USUARIO_REGISTRA;

CREATE SEQUENCE SEC_EJECUCION_VIAJES_PROYECTO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999;

ALTER TABLE EJECUCION_VIAJES_PROYECTO MODIFY (FECHA_REGISTRO TIMESTAMP );

CREATE SEQUENCE SEC_EJECUCION_OTROS_GAST_PROY INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999;

ALTER TABLE CRITERIO_EVALUACION  
MODIFY (NOMBRE_CRITERIO VARCHAR2(120 BYTE) );

ALTER TABLE CRITERIO_EVALUACION  
MODIFY (DESCRIPCION_CRITERIO VARCHAR2(320 BYTE) );

ALTER TABLE CRITERIO_EVALUACION  
MODIFY (VALOR INTEGER );