ALTER TABLE ACTIVIDADES_PLAN_TRABAJO ADD ID_ESTADO NUMBER;
ALTER TABLE ACTIVIDADES_PLAN_TRABAJO ADD CONSTRAINT ID_ESTADO_ACT_IMPL_CONS_FK FOREIGN KEY (ID_ESTADO) REFERENCES CONSTANTES (ID_CONSTANTES);

ALTER TABLE ACTIVIDADES_PLAN_TRABAJO ADD PORCENTAJE NUMBER;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('269','TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL','Realizada','Realizada');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('270','TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL','No cumplida','No cumplida');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values ('271','TIPO_ESTADO_INFORME_ACTIVIDAD_IMPL','Parcialmente realizada','Parcialmente realizada');

DROP TABLE ACTIVIDADES_IMPLEMENTACION CASCADE CONSTRAINTS;
CREATE TABLE ACTIVIDADES_IMPLEMENTACION
  (
    ID_ACTIVIDAD_IMPLEMENTACION NUMBER NOT NULL ,
    ID_INFORME_AVANCE_IMPL      NUMBER NOT NULL ,
    ID_USUARIO_ROL            NUMBER NOT NULL ,
    ID_ACTIVIDAD_PLAN_TRABAJO NUMBER,
	ID_ESTADO_ACTIVIDAD       NUMBER,
    RESULTADO_ACTIVIDAD       VARCHAR2(4000 ),    
    FECHA_REAL_INICIO DATE,
    FECHA_REAL_FIN DATE,
    ARCHIVO_SOPORTE           VARCHAR2(100 ),
    EVIDENCIA_FOTOGRAFICA     VARCHAR2(100 ),
    PORC_CUMPLIMIENTO_PARCIAL NUMBER,
    NUEVA_FECHA_FINALIZACION DATE,
    JUSTIFICACION_PARCIAL VARCHAR2(4000 ),
    ACCIONES_ADEL_LOGRO   VARCHAR2(4000 ),
    NUEVA_FECHA_INICIO DATE,
    NUEVA_FECHA_FIN VARCHAR2(20 ),
	FECHA_REGISTRO TIMESTAMP,
	USUARIO  VARCHAR2(50 ),
    MAQUINA  VARCHAR2(100 ) NOT NULL ,
    CONSTRAINT ACTIVIDADES_IMPLEMENTACION_PK PRIMARY KEY (ID_ACTIVIDAD_IMPLEMENTACION) USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE SYSTEM ,
    CONSTRAINT ACTI_INFOR_AVANCE_IMPL_FK FOREIGN KEY (ID_INFORME_AVANCE_IMPL) REFERENCES IMPLEMENTACIONES_PROYECTO (ID_IMPLEMENTACION_PROY) ,
    CONSTRAINT ACTIVIDADES_IMPLEMENTACIO_FK1 FOREIGN KEY (ID_ACTIVIDAD_PLAN_TRABAJO) REFERENCES ACTIVIDADES_PLAN_TRABAJO (ID_ACTIV_PLAN_TRABAJO) ,
    CONSTRAINT ACTIVIDADES_IMPLEMENTACIO_FK2 FOREIGN KEY (ID_ESTADO_ACTIVIDAD) REFERENCES CONSTANTES (ID_CONSTANTES),
	CONSTRAINT ACTIVIDADES_IMPLEMENTACIO_FK3 FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL)
  );
COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ID_ACTIVIDAD_IMPLEMENTACION
IS
  'Identificador de actividad de implementación';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ID_INFORME_AVANCE_IMPL
IS
  'Informe de avance de implementación';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.FECHA_REGISTRO
IS
  'Fecha de registro';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ID_USUARIO_ROL
IS
  'Identificador de usuario rol que realiza el registro';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.USUARIO
IS
  'Usuario que hace la implementación';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.MAQUINA
IS
  'Máquina donde se genera la soliciitud';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ID_ACTIVIDAD_PLAN_TRABAJO
IS
  'Identificador de la actividad del plan de trabajo';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.RESULTADO_ACTIVIDAD
IS
  'Resultado de la actividad';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ID_ESTADO_ACTIVIDAD
IS
  'Identificador del estado de la actividad';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.FECHA_REAL_INICIO
IS
  'Fecha real de inicio de la actividad';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.FECHA_REAL_FIN
IS
  'Fecha real de finalización de la actividad';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ARCHIVO_SOPORTE
IS
  'Archivo de soporte';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.EVIDENCIA_FOTOGRAFICA
IS
  'Evidencia fotográfica de la actividad';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.PORC_CUMPLIMIENTO_PARCIAL
IS
  'Porcentaje de cumplimiento de la actividad';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.NUEVA_FECHA_FINALIZACION
IS
  'Nueva fecha de finalización cuando la actividad se hace parcialmente';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.JUSTIFICACION_PARCIAL
IS
  'Justificación por la cual la actividad se realiza parcialmente';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.ACCIONES_ADEL_LOGRO
IS
  'Acciones adelantadas para el logro en caso de que la actividad no se cumpla';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.NUEVA_FECHA_INICIO
IS
  'Nueva fecha de inicio para actividad no cumplida';
  COMMENT ON COLUMN ACTIVIDADES_IMPLEMENTACION.NUEVA_FECHA_FIN
IS
  'Nueva fecha fin de la actividad no cumplida';

ALTER TABLE INVESTIGADORES_PROYECTO ADD HORAS_TOTALES_IMPL NUMBER;
ALTER TABLE INVESTIGADORES_PROYECTO ADD HORAS_DEDICADA_AVANCE_IMPL NUMBER;
ALTER TABLE INVESTIGADORES_PROYECTO ADD HORAS_DEDICADA_AVANC_FIN_IMPL NUMBER;

DROP TABLE INDICADORES_INFORME_AVANCE_IMP CASCADE CONSTRAINTS;
CREATE TABLE INDICADORES_INFORME_AVANCE_IMP
  (
    ID_INDICADORES_AVANCE_IMPL NUMBER NOT NULL ,    
    ID_INDICADOR_PLAN_TRABAJO  NUMBER NOT NULL ,
	ID_INFORME_AVANCE_IMPL  NUMBER NOT NULL ,
    VALOR_NUMERADOR            NUMBER,
    VALOR_DENOMINADOR          VARCHAR2(20 ),
    CONSTRAINT INDICADORES_INFORME_AVANCE_PK PRIMARY KEY (ID_INDICADORES_AVANCE_IMPL) ,
    CONSTRAINT INDICADORES_INFORME_AVANC_FK1 FOREIGN KEY (ID_INDICADOR_PLAN_TRABAJO) REFERENCES INDICADORES_PLAN_TRABAJO (ID_INDICADOR_PLAN_TRAB),
	CONSTRAINT INDICADORES_INFORME_AVANC_FK2 FOREIGN KEY (ID_INFORME_AVANCE_IMPL) REFERENCES INFORME_AVANCE_IMPLEMENTACION (ID_INFORME_AVANCE_IMPL) 	
  );

CREATE SEQUENCE SEC_INDICADOR_INFOR_AVANCE_IMP
  INCREMENT by 1
  MINVALUE 1
;

ALTER TABLE TEMA_PROYECTO ADD TIPO_TAB_INFORMACION_IMPL VARCHAR2(100);

-- envio correos
ALTER TABLE CORREO_ENVIO 
ADD (NOMBRE_ADJUNTO VARCHAR2(100) );

ALTER TABLE CORREO_ENVIO 
ADD (CONTENIDO_ADJUNTO BLOB );

-- mensajes error validaciones compromiso periodo

INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_necesidades_error_formulacion_requerida', 'Mesaje error formulacion requerida Necesidades');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_necesidades_error_formulacion_multiple', 'Mesaje error formulacion multiple Necesidades');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_necesidades_error_informe_avance_requerido', 'Mesaje error informe avance requerido Necesidades');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_necesidades_error_informe_final_requerido', 'Mesaje error informe final requerido Necesidades');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_necesidades_error_informe_final_multiple', 'Mesaje error informe avance multiple Necesidades');

INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_convocatorias_error_formulacion_multiple', 'Mesaje error formulacion multiple Convocatorias');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_convocatorias_error_informe_avance_requerido', 'Mesaje error informe avance requerido Convocatorias');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_convocatorias_error_informe_final_requerido', 'Mesaje error informe final requerido Convocatorias');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_convocatorias_error_informe_final_multiple', 'Mesaje error informe final multiple Convocatorias');

INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_convocatorias_error_no_compromisos', 'Mesaje error no comprmisos periodo Convocatorias');
INSERT INTO KEY_PROPERTIES (CLAVE, VALOR) VALUES ('validacion_necesidades_error_no_compromisos', 'Mesaje error no comprmisos periodo Necesidades');