DROP TABLE DOCUMENTACION_PROYECTO CASCADE CONSTRAINTS;
CREATE TABLE DOCUMENTACION_PROYECTO
  (
    ID_DOCUM_PROYECTO NUMBER NOT NULL ,
    ID_TIPO_DOCUMENTO NUMBER NOT NULL ,
    ID_PROYECTO       NUMBER NOT NULL,
    NOMBRE_ARCHIVO_USUARIO      VARCHAR2(100 ),
    NOMBRE_ARCHIVO_FISICO       VARCHAR2(100 ),
    DESCRIPCION       VARCHAR2(512),
    FECHA_PRESENTACION DATE NOT NULL ,
    ID_USUARIO_ROL       NUMBER NOT NULL ,
    COMENTARIO_DOCUMENTO VARCHAR2(512),
    MAQUINA VARCHAR2(100) NOT NULL,	
    CONSTRAINT DOCUMENTACION_PROYECTO_PK PRIMARY KEY (ID_DOCUM_PROYECTO), 
	CONSTRAINT FK_TIPO_DOCU_CONSTANTE FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES CONSTANTES (ID_CONSTANTES),
    CONSTRAINT FK_ID_PROYECTO_DOCU_PROY FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
	CONSTRAINT FK_ID_USUARIOROL_DOCU_PROY FOREIGN KEY (ID_USUARIO_ROL) REFERENCES USUARIO_ROL (ID_USUARIO_ROL)
  );
  
  CREATE SEQUENCE SEC_DOCUMENTACION_PROYECTO
  INCREMENT by 1
  MINVALUE 1
;

Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (206,'TIPO_DOCUMENTO_TRABAJO_GRADO','Informe de avance','Informe de avance');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (207,'TIPO_DOCUMENTO_TRABAJO_GRADO','Trabajo de grado/Informe final','Trabajo de grado/Informe final');
Insert into CONSTANTES (ID_CONSTANTES,TIPO,CODIGO,VALOR) values (208,'TIPO_DOCUMENTO_TRABAJO_GRADO','Acta de sustentación','Acta de sustentación');

ALTER TABLE COMENTARIO_PROYECTO ADD ID_DOCUMENTACION_PROYECTO NUMBER;

ALTER TABLE COMENTARIO_PROYECTO ADD CONSTRAINT DOCUMEN_PRO_COMENTARIO_FK FOREIGN KEY (ID_DOCUMENTACION_PROYECTO) REFERENCES DOCUMENTACION_PROYECTO (ID_DOCUM_PROYECTO);

ALTER TABLE PERSONAL_IMPLEMENTACION ADD NOMBRE_COMPLETO VARCHAR2(200);
ALTER TABLE PERSONAL_IMPLEMENTACION ADD CORREO VARCHAR2(100);

Insert into OPCION_MENU (ID_OPCION_MENU,NOMBRE,TIPO_ACCESO,ACCION,ID_OPCION_MENU2,ORDEN,TITULO) values (30,'Evaluar ensayo crítico','PRIVADO','BEAN:#{cuCo8EvaluacionEnsayoCriticoFaces.initReturnCU}',2,4,'Listar los ensayos críticos para evaluación.');

Insert into ROL_OPCION_MENU (ID_ROL_OPCION_MENU,ID_ROL,ID_OPCION_MENU) values (32,8,30);
Insert into ROL_OPCION_MENU (ID_ROL_OPCION_MENU,ID_ROL,ID_OPCION_MENU) values (33,8,2);

CREATE SEQUENCE SEC_ACTIVIDAD_IMPLEMENTACION
  INCREMENT by 1
  MINVALUE 1;